"""Document generators.

Each generator composes what MetaBridge already knows — the parsed IR,
the Digital Twin, the governance classifier, lineage — into a canonical
Doc. Generators never render; the renderers in render.py turn a Doc into
PDF / Word / Markdown / HTML. Deterministic: no timestamps unless the
caller supplies one, so the same estate always produces byte-identical
documents.
"""
from __future__ import annotations

from typing import Dict, List, Optional

from ..ir.model import Pipeline, TransformationType
from ..twin.model import DigitalTwin, twin_from_dict
from .model import Doc

# slug -> (title, generator) — declaration order is the catalog order
DOC_TYPES: "Dict[str, tuple]" = {}


def _doc_type(slug, title):
    def deco(fn):
        DOC_TYPES[slug] = (title, fn)
        return fn
    return deco


# ---------------------------------------------------------------------------
# context
# ---------------------------------------------------------------------------

def build_context(pipelines: Optional[list] = None, twin=None,
                  project: str = "", generated_at: str = "",
                  job_id: str = "", source_ref: str = "",
                  source_snapshot: str = "") -> dict:
    pipelines = pipelines or []
    if isinstance(pipelines, Pipeline):
        pipelines = [pipelines]
    if isinstance(twin, dict):
        twin = twin_from_dict(twin)
    if twin is None:
        twin = DigitalTwin(project or "estate")
    if not project:
        project = (pipelines[0].name if pipelines else twin.name) or "estate"
    return {"pipelines": pipelines, "twin": twin, "project": project,
            "generated_at": generated_at, "job_id": job_id,
            "source_ref": source_ref, "source_snapshot": source_snapshot}


def _meta(ctx: dict) -> dict:
    m = {"Project": ctx["project"],
         "Generated by": "MetaBridge AI"}
    if ctx.get("job_id"):
        m["Job ID"] = ctx["job_id"]
    if ctx.get("source_ref"):
        m["Source"] = ctx["source_ref"]
    if ctx["pipelines"]:
        fmts = sorted({p.source_format for p in ctx["pipelines"]
                       if p.source_format})
        if fmts:
            m["Source format"] = ", ".join(fmts)
    if ctx["generated_at"]:
        m["Generated"] = ctx["generated_at"]
    if ctx.get("source_snapshot"):
        m["Source snapshot"] = ctx["source_snapshot"]
    return m


def _all_mappings(ctx):
    return [(p, m) for p in ctx["pipelines"] for m in p.mappings]


def _xf(m):
    return [t for t in m.transformations if t.name != "__OUTPUT__"]


def _classifications(ctx):
    out = []
    try:
        from ..governance.engine import classify_pipeline
        for p in ctx["pipelines"]:
            out += [(p, c) for c in classify_pipeline(p)]
    except Exception:  # noqa: BLE001 — governance optional
        pass
    return out


def _empty_note(d: Doc, what: str) -> Doc:
    return d.note("No %s available in the analyzed metadata. Upload the "
                  "relevant project or build a Digital Twin to populate "
                  "this section." % what)


def _cap(d: Doc, items: list, cap: int, what: str) -> list:
    """Return at most ``cap`` items, and — critically — DISCLOSE the
    truncation in the document. A delivered document must never state a
    total and then silently list fewer (the product's own 'never
    silently dropped' principle)."""
    if len(items) > cap:
        d.note("Showing the first %d of %d %s. Generate the JSON export "
               "or narrow the scope for the complete set."
               % (cap, len(items), what))
        return items[:cap]
    return items


# ---------------------------------------------------------------------------
# 1. Architecture
# ---------------------------------------------------------------------------

@_doc_type("architecture", "Architecture Document")
def gen_architecture(ctx) -> Doc:
    from ..twin import analyze
    twin = ctx["twin"]
    d = Doc("Architecture Document",
            "Current-state data estate architecture", _meta(ctx))
    d.h("Overview")
    counts = twin.counts()
    d.p("The data estate comprises %d catalogued object(s) across the "
        "layers below, discovered from the analyzed sources."
        % (len(twin.nodes)))
    if not twin.nodes:
        return _empty_note(d, "estate graph")
    d.kv([(k, v) for k, v in counts.items() if k != "edges"])

    d.h("Technology inventory")
    inv = analyze.technology_inventory(twin)
    if inv["technologies"]:
        d.table(["Technology", "Objects", "Breakdown"],
                [[t["technology"], t["total"],
                  ", ".join("%s: %d" % (k, v)
                            for k, v in t["by_kind"].items())]
                 for t in inv["technologies"]])
    d.h("Application landscape")
    land = analyze.application_landscape(twin)
    if land["applications"]:
        d.table(["Application", "Technology", "Domain", "Owner",
                 "Pipelines", "Tables", "Topics"],
                [[a["application"], a["technology"] or "—",
                  a["domain"], a["owner"] or "—", a["pipelines"],
                  a["tables"], a["topics"]]
                 for a in land["applications"]])
    else:
        d.p("No applications catalogued.")
    d.h("Application dependencies")
    dep = analyze.application_dependency_graph(twin)
    if dep["dependencies"]:
        d.table(["Application", "Depends on", "Via"],
                [[x["application"], x["depends_on"],
                  "; ".join(x["via"][:3])] for x in dep["dependencies"]])
    else:
        d.p("No cross-application data dependencies detected.")
    d.note("Architecture is derived from estate topology (the Digital "
           "Twin), not runtime telemetry.")
    return d


# ---------------------------------------------------------------------------
# 2. Source-to-Target Mapping
# ---------------------------------------------------------------------------

@_doc_type("source_to_target_mapping", "Source-to-Target Mapping")
def gen_stm(ctx) -> Doc:
    d = Doc("Source-to-Target Mapping",
            "Column-level source-to-target field mapping", _meta(ctx))
    mappings = _all_mappings(ctx)
    if not mappings:
        return _empty_note(d, "pipeline mappings")
    for p, m in mappings:
        d.h("%s" % m.name, 2)
        srcs = [t for t in m.transformations
                if t.type == TransformationType.SOURCE]
        tgts = [t for t in m.transformations
                if t.type == TransformationType.TARGET]
        d.kv([("Load strategy", m.load_strategy.value),
              ("Sources", ", ".join(str(t.properties.get("table", t.name))
                                     for t in srcs) or "—"),
              ("Targets", ", ".join(str(t.properties.get("table", t.name))
                                     for t in tgts) or "—")])
        rows = []
        for t in tgts:
            for port in t.ports:
                rows.append([str(t.properties.get("table", t.name)),
                             port.name, port.datatype,
                             port.expression or "(pass-through)"])
        if rows:
            d.table(["Target table", "Target column", "Type",
                     "Derivation"], rows)
        else:
            d.p("No target columns declared for this mapping.")
    return d


# ---------------------------------------------------------------------------
# 3. Technical Design Document
# ---------------------------------------------------------------------------

@_doc_type("technical_design", "Technical Design Document")
def gen_tdd(ctx) -> Doc:
    d = Doc("Technical Design Document",
            "Per-object transformation design", _meta(ctx))
    mappings = _all_mappings(ctx)
    if not mappings:
        return _empty_note(d, "pipeline mappings")
    d.h("Execution order")
    for p in ctx["pipelines"]:
        waves = p.execution_order()
        if waves:
            d.p("%s:" % p.name)
            d.bullets(["Wave %d: %s" % (i + 1, ", ".join(w))
                       for i, w in enumerate(waves)])
    for p, m in mappings:
        d.h(m.name, 2)
        if m.description:
            d.p(m.description)
        d.kv([("Load strategy", m.load_strategy.value),
              ("Unique key", ", ".join(m.unique_key) or "—"),
              ("Depends on", ", ".join(m.depends_on) or "—"),
              ("Transformations", str(len(_xf(m))))])
        rows = []
        for t in _xf(m):
            detail = ""
            for k in ("condition", "join_type", "group_by", "sql_override",
                      "strategy"):
                v = t.properties.get(k)
                if v:
                    detail = "%s: %s" % (k, str(v)[:80])
                    break
            rows.append([t.name, t.type.value, detail or "—"])
        if rows:
            d.table(["Step", "Type", "Logic"], rows)
    return d


# ---------------------------------------------------------------------------
# 4. Solution Design Document
# ---------------------------------------------------------------------------

@_doc_type("solution_design", "Solution Design Document")
def gen_sdd(ctx) -> Doc:
    twin = ctx["twin"]
    d = Doc("Solution Design Document",
            "Target-state solution & modernization approach", _meta(ctx))
    d.h("Solution summary")
    n_map = sum(len(p.mappings) for p in ctx["pipelines"])
    n_src = sum(len(p.sources) for p in ctx["pipelines"])
    d.p("This solution modernizes %d pipeline object(s) reading from %d "
        "source table(s), catalogued across a %d-object estate graph."
        % (n_map, n_src, len(twin.nodes)))
    d.h("Design principles")
    d.bullets([
        "Single canonical intermediate representation — every source "
        "parses into it and every target generates from it (no pairwise "
        "converters).",
        "Honest degradation — anything that cannot be auto-translated is "
        "declared as a manual item, never silently dropped.",
        "Governance-first — sensitive data is classified and protected "
        "before it lands in the target.",
        "Deterministic, evidence-based analysis — figures trace to "
        "metadata or a labelled assumption."])
    d.h("Load strategies in scope")
    strat: Dict[str, int] = {}
    for p in ctx["pipelines"]:
        for m in p.mappings:
            strat[m.load_strategy.value] = \
                strat.get(m.load_strategy.value, 0) + 1
    if strat:
        d.table(["Load strategy", "Objects"],
                [[k, v] for k, v in sorted(strat.items(),
                                           key=lambda x: -x[1])])
    d.h("Manual-review items")
    from ..ir.model import IssueSeverity
    manual = [i for p in ctx["pipelines"] for i in p.all_issues()
              if i.severity in (IssueSeverity.MANUAL, IssueSeverity.ERROR)]
    if manual:
        d.p("%d item(s) require manual design decisions:" % len(manual))
        shown = _cap(d, manual, 20, "manual-review items")
        d.bullets(["[%s] %s — %s" % (i.severity.value, i.code, i.message)
                   for i in shown])
    else:
        d.p("No manual-review items — the solution is fully "
            "auto-translatable from the analyzed metadata.")
    return d


# ---------------------------------------------------------------------------
# 5. Migration Runbook
# ---------------------------------------------------------------------------

@_doc_type("migration_runbook", "Migration Runbook")
def gen_runbook(ctx) -> Doc:
    d = Doc("Migration Runbook",
            "Step-by-step migration execution & rollback", _meta(ctx))
    d.h("Pre-migration checklist")
    d.bullets([
        "Confirm target landing zone, connections and credentials "
        "(externalized in a secret manager).",
        "Snapshot source objects and record row counts for "
        "reconciliation.",
        "Freeze source schema changes for the cutover window.",
        "Provision CI/CD and a parallel-run environment."])
    if not ctx["pipelines"]:
        _empty_note(d, "pipeline execution order")
    for p in ctx["pipelines"]:
        waves = p.execution_order()
        if not waves:
            continue
        d.h("Execution waves — %s" % p.name, 2)
        d.p("Run each wave in order; every object in a wave may run in "
            "parallel. Reconcile row counts before advancing.")
        d.table(["Wave", "Objects", "Cutover note"],
                [[i + 1, ", ".join(w),
                  "parallel-run + reconcile" if i + 1 < len(waves)
                  else "final wave — decommission source after sign-off"]
                 for i, w in enumerate(waves)])
    d.h("Rollback")
    d.bullets([
        "Halt at the failed wave; the target is populated only up to the "
        "last reconciled wave.",
        "Re-point consumers to the source (parallel-run keeps it live).",
        "Preserve target artifacts + logs for root-cause before retry."])
    d.note("Confirm 'unused'/idle assets against runtime access logs "
           "before decommissioning any source.")
    return d


# ---------------------------------------------------------------------------
# 6. Deployment Guide
# ---------------------------------------------------------------------------

@_doc_type("deployment_guide", "Deployment Guide")
def gen_deployment(ctx) -> Doc:
    d = Doc("Deployment Guide",
            "How to deploy the generated artifacts", _meta(ctx))
    d.h("Environments")
    d.bullets(["dev — validate generated artifacts against sampled data",
               "staging — full parallel-run and reconciliation",
               "prod — cutover after sign-off"])
    d.h("Connections")
    conns = []
    for p in ctx["pipelines"]:
        conns += list(p.metadata.get("connections", []) or [])
    twin_conns = [n.name for n in ctx["twin"].nodes.values()
                  if n.kind == "connection"]
    names = sorted({(c.get("name") if isinstance(c, dict) else str(c))
                    for c in conns} | set(twin_conns))
    if names:
        d.p("Configure the following connections (credentials via a "
            "secret manager, never inline):")
        d.bullets(names)
    else:
        d.p("No connections catalogued — declare target connections "
            "before deployment.")
    d.h("Deployment steps")
    d.bullets([
        "Provision target schemas / warehouses.",
        "Deploy generated pipeline artifacts via CI/CD (versioned).",
        "Load reference / dimension data first.",
        "Run the pipelines in execution-wave order (see the runbook).",
        "Enable orchestration schedules once validation passes."])
    return d


# ---------------------------------------------------------------------------
# 7. Operations Manual
# ---------------------------------------------------------------------------

@_doc_type("operations_manual", "Operations Manual")
def gen_operations(ctx) -> Doc:
    d = Doc("Operations Manual",
            "Run, monitor and troubleshoot the pipelines", _meta(ctx))
    d.h("Scheduling & orchestration")
    dags = [dag for p in ctx["pipelines"]
            for dag in (p.metadata.get("workflow_dags", []) or [])]
    workflows = [n.name for n in ctx["twin"].nodes.values()
                 if n.kind == "workflow"]
    if dags or workflows:
        d.bullets(sorted({str(dag.get("workflow", "workflow"))
                          for dag in dags} | set(workflows)))
    else:
        d.p("No orchestration workflows catalogued.")
    d.h("Monitoring")
    d.bullets([
        "Track run status, duration and row counts per pipeline.",
        "Alert on run failure, SLA breach and reconciliation mismatch.",
        "Watch warehouse utilization and credit spend (see the FinOps "
        "report)."])
    d.h("Common issues")
    d.table(["Symptom", "Likely cause", "Action"],
            [["Pipeline fails on load", "schema drift / null key",
              "check source schema + unique key"],
             ["Row-count mismatch", "filter or incremental window",
              "reconcile against source snapshot"],
             ["Slow run", "full refresh where incremental fits",
              "review load strategy"],
             ["Access denied", "credential rotation / grant",
              "verify secret manager + role grants"]])
    return d


# ---------------------------------------------------------------------------
# 8. Business Glossary
# ---------------------------------------------------------------------------

@_doc_type("business_glossary", "Business Glossary")
def gen_glossary(ctx) -> Doc:
    twin = ctx["twin"]
    d = Doc("Business Glossary",
            "Business domains, terms and ownership", _meta(ctx))
    domains = [n for n in twin.nodes.values() if n.kind == "domain"]
    products = [n for n in twin.nodes.values() if n.kind == "data_product"]
    if domains:
        d.h("Business domains")
        d.table(["Domain", "Owner", "Declared"],
                [[n.name, n.owner or "—",
                  "no (inferred)" if n.inferred else "yes"]
                 for n in sorted(domains, key=lambda x: x.name)])
    if products:
        d.h("Data products")
        d.table(["Data product", "Owner"],
                [[n.name, n.owner or "—"]
                 for n in sorted(products, key=lambda x: x.name)])
    # described objects double as glossary terms
    terms = []
    for p in ctx["pipelines"]:
        for m in p.mappings:
            if (m.description or "").strip():
                terms.append([m.name, m.description])
    if terms:
        d.h("Defined terms")
        d.table(["Term", "Definition"], terms)
    if not (domains or products or terms):
        _empty_note(d, "business domains, products or descriptions")
        d.note("Add an estate.yml descriptor (domains, owners, data "
               "products) and object descriptions to enrich the "
               "glossary.")
    return d


# ---------------------------------------------------------------------------
# 9. Data Dictionary
# ---------------------------------------------------------------------------

def _type_str(port) -> str:
    """Column type including declared precision/scale when present."""
    dt = port.datatype
    if getattr(port, "precision", 0):
        if dt == "decimal":
            return "%s(%d,%d)" % (dt, port.precision, getattr(port, "scale", 0))
        return "%s(%d)" % (dt, port.precision)
    return dt


@_doc_type("data_dictionary", "Data Dictionary")
def gen_data_dictionary(ctx) -> Doc:
    from ..ir.model import TransformationType
    d = Doc("Data Dictionary",
            "Source & target tables, columns, types, lineage and "
            "transformation metadata", _meta(ctx))
    # column -> classification category (from governance)
    cls = {}
    for p, c in _classifications(ctx):
        cls[c.column.lower()] = c.category

    src_tables = 0
    tgt_tables = 0

    # --- Source tables ---------------------------------------------------
    d.h("Source tables", 2)
    seen = set()
    for p in ctx["pipelines"]:
        for s in p.sources:
            key = (s.database, s.schema, s.name)
            if key in seen:
                continue
            seen.add(key)
            src_tables += 1
            qualified = ".".join(x for x in (s.database, s.schema, s.name) if x)
            d.h(qualified, 3)
            if s.columns:
                d.table(["Column", "Type", "Nullable", "Classification"],
                        [[c.name, _type_str(c),
                          "yes" if c.nullable else "no",
                          cls.get(c.name.lower(), "—")]
                         for c in s.columns])
            else:
                d.p("No columns catalogued for this table (schema not "
                    "introspected).")
    if not src_tables:
        d.p("No source tables catalogued in the current project.")

    # --- Target tables (from each mapping's TARGET transformation) -------
    d.h("Target tables", 2)
    for p in ctx["pipelines"]:
        for m in p.mappings:
            for t in m.by_type(TransformationType.TARGET):
                tgt_tables += 1
                name = str(t.properties.get("table", t.name))
                d.h(name, 3)
                if t.ports:
                    d.table(["Column", "Type", "Nullable", "Key"],
                            [[c.name, _type_str(c),
                              "yes" if c.nullable else "no",
                              "PK" if c.name in m.unique_key else "—"]
                             for c in t.ports])
                else:
                    d.p("No target columns catalogued.")
    if not tgt_tables:
        d.p("No target tables catalogued in the current project.")

    # --- Transformation metadata + lineage -------------------------------
    d.h("Transformations & lineage", 2)
    any_mapping = False
    for p in ctx["pipelines"]:
        for m in p.mappings:
            any_mapping = True
            steps = [t for t in m.transformations if t.name != "__OUTPUT__"]
            srcs = [str(t.properties.get("table", t.name))
                    for t in m.by_type(TransformationType.SOURCE)]
            tgts = [str(t.properties.get("table", t.name))
                    for t in m.by_type(TransformationType.TARGET)]
            d.h(m.name, 3)
            rows = [
                ["Load strategy", getattr(m.load_strategy, "value",
                                          str(m.load_strategy))],
                ["Unique key", ", ".join(m.unique_key) or "—"],
                ["Sources", ", ".join(srcs) or "—"],
                ["Targets", ", ".join(tgts) or "—"],
                ["Depends on", ", ".join(m.depends_on) or "—"],
                ["Transformation steps",
                 ", ".join("%s(%s)" % (t.name, getattr(t.type, "value",
                                                       str(t.type)))
                           for t in steps) or "—"],
            ]
            d.kv(rows)
            if m.description:
                d.p(m.description)
    if not any_mapping:
        d.p("No transformations catalogued in the current project.")

    # --- Coverage / warning ----------------------------------------------
    if not (src_tables or tgt_tables or any_mapping):
        d.h("Coverage", 2)
        d.note("No table, column or transformation metadata was available in "
               "the analyzed project. This can happen when the upload has no "
               "column definitions or the source could not be parsed. Add "
               "column metadata to the manifest, or point the connector at "
               "the live system to introspect, then regenerate.")
    else:
        cov = ("Coverage: %d source table(s), %d target table(s), %d "
               "mapping(s)." % (src_tables, tgt_tables,
                                sum(len(p.mappings) for p in ctx["pipelines"])))
        missing = sum(1 for p in ctx["pipelines"] for s in p.sources
                      if not s.columns)
        if missing:
            cov += (" %d source table(s) have no column metadata — shown "
                    "without columns above." % missing)
        d.note(cov + " Classification is heuristic (column-name based) — "
               "confirm with a content scan before relying on it for "
               "compliance.")
    return d


# ---------------------------------------------------------------------------
# 10. API Documentation
# ---------------------------------------------------------------------------

@_doc_type("api_documentation", "API Documentation")
def gen_api_docs(ctx) -> Doc:
    twin = ctx["twin"]
    d = Doc("API Documentation",
            "Data-serving APIs in the estate", _meta(ctx))
    apis = [n for n in twin.nodes.values() if n.kind == "api"]
    if apis:
        d.h("Estate APIs")
        for n in sorted(apis, key=lambda x: x.name):
            d.h(n.name, 2)
            reads = [twin.nodes[e.from_id].name
                     for e in twin.in_edges(n.id) if e.kind == "feeds"]
            serves = [twin.nodes[e.to_id].name
                      for e in twin.out_edges(n.id) if e.kind == "serves"]
            d.kv([("Technology", n.technology or "—"),
                  ("Owner", n.owner or "—"),
                  ("Reads", ", ".join(reads) or "—"),
                  ("Serves", ", ".join(serves) or "—")])
    else:
        d.p("No data-serving APIs catalogued in the estate graph.")
    d.h("MetaBridge platform API")
    d.p("The MetaBridge REST API exposes the modernization and "
        "intelligence engines. Representative endpoints:")
    d.table(["Method", "Endpoint", "Purpose"],
            [["POST", "/api/convert", "convert a source project to a "
              "target"],
             ["POST", "/api/twin/build", "build the estate Digital Twin"],
             ["POST", "/api/assessment", "migration assessment"],
             ["POST", "/api/security", "security & compliance analysis"],
             ["POST", "/api/docs", "generate documentation (this "
              "document)"]])
    d.note("Estate-API detail is limited to what the metadata / estate "
           "descriptor declares; annotate APIs in estate.yml for fuller "
           "documentation.")
    return d


# ---------------------------------------------------------------------------
# 11. Pipeline Documentation
# ---------------------------------------------------------------------------

@_doc_type("pipeline_documentation", "Pipeline Documentation")
def gen_pipeline_docs(ctx) -> Doc:
    d = Doc("Pipeline Documentation",
            "Purpose, inputs, outputs and lineage per pipeline",
            _meta(ctx))
    mappings = _all_mappings(ctx)
    if not mappings:
        return _empty_note(d, "pipelines")
    for p, m in mappings:
        d.h(m.name, 2)
        if m.description:
            d.p(m.description)
        srcs = sorted({str(t.properties.get("table", t.name))
                       for t in m.by_type(TransformationType.SOURCE)})
        tgts = sorted({str(t.properties.get("table", t.name))
                       for t in m.by_type(TransformationType.TARGET)})
        lkps = sorted({str(t.properties.get("table", t.name))
                       for t in m.by_type(TransformationType.LOOKUP)})
        d.kv([("Inputs", ", ".join(srcs) or "—"),
              ("Lookups", ", ".join(lkps) or "—"),
              ("Outputs", ", ".join(tgts) or "—"),
              ("Load strategy", m.load_strategy.value),
              ("Upstream dependencies", ", ".join(m.depends_on) or "—"),
              ("Transformation steps", str(len(_xf(m))))])
    return d


# ---------------------------------------------------------------------------
# 12. Validation Report
# ---------------------------------------------------------------------------

@_doc_type("validation_report", "Validation Report")
def gen_validation(ctx) -> Doc:
    from ..ir.model import IssueSeverity
    d = Doc("Validation Report",
            "Parse & conversion-readiness validation", _meta(ctx))
    issues = [i for p in ctx["pipelines"] for i in p.all_issues()]
    by_sev: Dict[str, int] = {}
    for i in issues:
        by_sev[i.severity.value] = by_sev.get(i.severity.value, 0) + 1
    d.h("Summary")
    n_obj = sum(len(p.mappings) for p in ctx["pipelines"])
    d.kv([("Objects analyzed", str(n_obj)),
          ("Total issues", str(len(issues))),
          ("Errors", str(by_sev.get("ERROR", 0))),
          ("Manual", str(by_sev.get("MANUAL", 0))),
          ("Warnings", str(by_sev.get("WARNING", 0)))])
    blocking = [i for i in issues
                if i.severity in (IssueSeverity.ERROR,
                                  IssueSeverity.MANUAL)]
    if blocking:
        d.h("Blocking / manual items")
        shown = _cap(d, blocking, 60, "blocking / manual items")
        d.table(["Severity", "Object", "Code", "Message"],
                [[i.severity.value, i.obj or "—", i.code, i.message]
                 for i in shown])
    else:
        d.p("No blocking or manual items detected in the analyzed "
            "metadata.")
    d.note("This validates parse & conversion readiness from metadata. "
           "Full source-vs-target equivalence (schema, row counts, "
           "aggregates) requires running the generated target against "
           "sampled data.")
    return d


# ---------------------------------------------------------------------------
# 13. Lineage Report
# ---------------------------------------------------------------------------

@_doc_type("lineage_report", "Lineage Report")
def gen_lineage(ctx) -> Doc:
    from ..report import lineage as lin
    d = Doc("Lineage Report",
            "Table- and column-level data lineage", _meta(ctx))
    any_lin = False
    for p in ctx["pipelines"]:
        try:
            tl = lin.table_lineage(p)
        except Exception:  # noqa: BLE001
            tl = None
        edges = (tl or {}).get("edges") or []
        if edges:
            any_lin = True
            d.h("Table lineage — %s" % p.name, 2)
            shown = _cap(d, edges, 80, "table-lineage edges")
            d.table(["Source", "Target", "Via"],
                    [[e.get("from", e.get("source", "")),
                      e.get("to", e.get("target", "")),
                      e.get("mapping", e.get("via", ""))]
                     for e in shown])
    # column lineage summary from the twin flow edges as a fallback
    twin = ctx["twin"]
    flow = [(twin.nodes[e.from_id].name, e.kind, twin.nodes[e.to_id].name)
            for e in twin.edges.values()
            if e.kind in ("feeds", "writes", "reads", "produces",
                          "consumes")]
    if flow:
        any_lin = True
        d.h("Estate data flow")
        shown = _cap(d, flow, 120, "data-flow edges")
        d.table(["From", "Relationship", "To"],
                [[a, k, b] for a, k, b in shown])
    if not any_lin:
        _empty_note(d, "lineage")
    return d


# ---------------------------------------------------------------------------
# 14. Governance Report
# ---------------------------------------------------------------------------

@_doc_type("governance_report", "Governance Report")
def gen_governance(ctx) -> Doc:
    d = Doc("Governance Report",
            "Data classification, policy & processing register",
            _meta(ctx))
    cls = _classifications(ctx)
    d.h("Classification summary")
    if cls:
        by_cat: Dict[str, int] = {}
        for _, c in cls:
            by_cat[c.category] = by_cat.get(c.category, 0) + 1
        special = sum(1 for _, c in cls
                      if c.category.startswith("pii.special"))
        d.kv([("Classified columns", str(len(cls))),
              ("Distinct categories", str(len(by_cat))),
              ("Special-category (GDPR Art.9)", str(special))])
        d.h("Classified columns", 2)
        shown = _cap(d, cls, 80, "classified columns")
        d.table(["Mapping", "Column", "Category", "GDPR", "HIPAA"],
                [[c.mapping, c.column, c.category, c.gdpr or "—",
                  c.hipaa or "—"] for _, c in shown])
    else:
        d.p("No sensitive columns detected by name heuristics.")
    # processing register (per pipeline)
    try:
        from ..governance.engine import govern
        reg_rows = []
        for p in ctx["pipelines"]:
            for a in govern(p).get("processing_register", []):
                if a.get("data_categories"):
                    reg_rows.append([a["activity"],
                                     ", ".join(a["source_systems"]),
                                     ", ".join(a["target_systems"]),
                                     ", ".join(a["data_categories"])])
        if reg_rows:
            d.h("Record of processing activities (Art.30 style)", 2)
            shown = _cap(d, reg_rows, 60, "processing activities")
            d.table(["Activity", "Sources", "Targets", "Data categories"],
                    shown)
    except Exception:  # noqa: BLE001
        pass
    d.note("Automated inventory from pipeline metadata — input for the "
           "DPO / privacy office, not legal advice.")
    return d


# ---------------------------------------------------------------------------
# orchestration
# ---------------------------------------------------------------------------

def generate_document(slug: str, ctx: dict) -> Doc:
    if slug not in DOC_TYPES:
        raise ValueError("unknown document type: %s" % slug)
    return DOC_TYPES[slug][1](ctx)


def generate_all(ctx: dict, slugs: Optional[List[str]] = None
                 ) -> "Dict[str, Doc]":
    slugs = slugs or list(DOC_TYPES)
    return {s: generate_document(s, ctx) for s in slugs
            if s in DOC_TYPES}


def catalog() -> List[dict]:
    return [{"slug": s, "title": t} for s, (t, _) in DOC_TYPES.items()]
