"""Orchestration target generators (Command 6, §5) — everything FROM COR.

    airflow          runnable DAG .py (schedule, retries, SLAs, task
                     groups for parallel waves, trigger rules for
                     failure paths, operator by task type)
    adf / fabric     pipeline JSON (activities + dependsOn conditions,
                     policy retry/timeout) + ScheduleTrigger JSON
    stepfunctions    ASL state machine (Retry/Catch, Choice, Parallel)
    controlm         Automation API JSON folder (events for deps)
    autosys          JIL (insert_job blocks, conditions, calendars)
    dbtcloud         job JSON (sequential steps + cron trigger)
    powercenter      workflow XML skeleton (tasks + links)
    idmc_taskflow    taskflow JSON (steps with onSuccess/onFailure)
    scaffold         pipeline scaffold YAML (engine-neutral)
    docs             execution documentation (markdown) + mermaid graph

Semantics that a target cannot express are written into the artifact as
explicit ``_metabridge_note`` fields / comments and surfaced as issues —
declared loss, never silent loss.
"""
from __future__ import annotations

import json
import re
from typing import Dict, List

from .cor import COR, Task, Workflow, normalize_cron
from .graph import to_mermaid

ORCH_TARGETS = ("airflow", "adf", "fabric", "stepfunctions", "controlm",
                "autosys", "dbtcloud", "powercenter", "idmc_taskflow",
                "scaffold")


def _pyid(s: str) -> str:
    s = re.sub(r"\W+", "_", s).strip("_") or "task"
    return ("t_" + s) if s[0].isdigit() else s


def _cron_of(wf: Workflow) -> str:
    for s in wf.schedules:
        if s.kind == "cron" and s.cron:
            return normalize_cron(s.cron)
        if s.kind == "interval" and s.interval_seconds:
            if s.interval_seconds % 86400 == 0:
                return "0 0 */%d * *" % max(1, s.interval_seconds // 86400) \
                    if s.interval_seconds > 86400 else "0 0 * * *"
            if s.interval_seconds % 3600 == 0:
                return "0 */%d * * *" % max(1, s.interval_seconds // 3600)
            return "*/%d * * * *" % max(1, s.interval_seconds // 60)
    return ""


# ===========================================================================
# Airflow
# ===========================================================================

_AF_OP = {"command": ("BashOperator", "bash_command"),
          "sql": ("SQLExecuteQueryOperator", "sql"),
          "mapping": ("BashOperator", "bash_command"),
          "copy": ("BashOperator", "bash_command"),
          "notebook": ("BashOperator", "bash_command"),
          "email": ("EmailOperator", None),
          "dummy": ("EmptyOperator", None),
          "wait": ("TimeDeltaSensor", None),
          "sensor": ("FileSensor", None),
          "subworkflow": ("TriggerDagRunOperator", None)}


def generate_airflow(wf: Workflow) -> str:
    cron = _cron_of(wf)
    lines = [
        '"""%s — generated by MetaBridge AI from %s.' % (wf.name,
                                                         wf.platform),
        "",
        "Scheduling, retries, timeouts, dependency kinds and failure",
        'paths carry over from the source; review _metabridge notes."""',
        "from datetime import timedelta",
        "from airflow import DAG",
        "from airflow.operators.bash import BashOperator",
        "from airflow.operators.empty import EmptyOperator",
        "from airflow.operators.email import EmailOperator",
        "from airflow.operators.trigger_dagrun import TriggerDagRunOperator",
        "from airflow.providers.common.sql.operators.sql import "
        "SQLExecuteQueryOperator",
        "from airflow.sensors.filesystem import FileSensor",
        "from airflow.sensors.time_delta import TimeDeltaSensor",
        "",
        "with DAG(",
        '    dag_id="%s",' % wf.name,
        '    schedule=%s,' % (repr(cron) if cron else "None"),
        "    catchup=False,",
        '    tags=["metabridge", "%s"],' % wf.platform,
        ") as dag:",
    ]
    failure_targets = {d.to_task for d in wf.dependencies
                       if d.kind == "failure"}
    for t in wf.tasks:
        op, payload_kw = _AF_OP.get(t.type, ("BashOperator",
                                             "bash_command"))
        var = _pyid(t.key)
        args = ['task_id="%s"' % t.key]
        if t.type in ("choice", "loop", "parallel", "approval",
                      "unknown"):
            op = "EmptyOperator"
            note = {"choice": "branch — port the condition as a "
                              "BranchPythonOperator",
                    "loop": "loop — port as dynamic task mapping "
                            "(.expand())",
                    "parallel": "parallel group container",
                    "approval": "approval gate — no Airflow-native "
                                "equivalent; use an external approval "
                                "sensor",
                    "unknown": "unsupported source task — port manually"}
            lines.append("    # MANUAL: %s (%s)" % (note[t.type], t.key))
        if op == "BashOperator":
            payload = str(t.action.get("command", "")
                          or t.action.get("mapping", "")
                          or t.action.get("notebook", "")
                          or "echo TODO_%s" % t.key)
            args.append("bash_command=%r" % payload[:300])
        elif op == "SQLExecuteQueryOperator":
            args.append("sql=%r" % str(t.action.get("sql",
                                                    "-- TODO"))[:300])
            if t.connection:
                args.append('conn_id="%s"' % t.connection)
        elif op == "EmailOperator":
            args.append('to="%s"' % str(t.action.get("to",
                                                     "oncall@example.com")))
            args.append('subject="%s failed"' % wf.name)
        elif op == "TriggerDagRunOperator":
            args.append('trigger_dag_id="%s"'
                        % str(t.action.get("workflow", "TODO")))
        elif op == "TimeDeltaSensor":
            args.append("delta=timedelta(seconds=%d)"
                        % int(t.action.get("seconds", 60) or 60))
        elif op == "FileSensor":
            args.append('filepath="%s"'
                        % str(t.action.get("filepath", "/tmp/ready")))
        if t.retry.max_attempts:
            args.append("retries=%d" % t.retry.max_attempts)
            if t.retry.interval_seconds:
                args.append("retry_delay=timedelta(seconds=%d)"
                            % t.retry.interval_seconds)
        if t.timeout_seconds:
            args.append("execution_timeout=timedelta(seconds=%d)"
                        % t.timeout_seconds)
        if t.sla_seconds:
            args.append("sla=timedelta(seconds=%d)" % t.sla_seconds)
        if t.resources.get("pool"):
            args.append('pool="%s"' % t.resources["pool"])
        if t.key in failure_targets:
            args.append('trigger_rule="one_failed"')
        lines.append("    %s = %s(%s)" % (var, op, ", ".join(args)))
    lines.append("")
    for d in wf.dependencies:
        lines.append("    %s >> %s%s" % (
            _pyid(d.from_task), _pyid(d.to_task),
            "  # %s%s" % (d.kind, ": " + d.condition[:80]
                          if d.condition else "")
            if d.kind != "success" else ""))
    return "\n".join(lines) + "\n"


# ===========================================================================
# ADF / Fabric
# ===========================================================================

_ADF_OUT = {"copy": "Copy", "sql": "Script", "mapping": "ExecuteDataFlow",
            "notebook": "DatabricksNotebook", "command": "WebActivity",
            "email": "WebActivity", "wait": "Wait",
            "choice": "IfCondition", "loop": "ForEach",
            "subworkflow": "ExecutePipeline", "sensor": "Validation",
            "dummy": "Wait", "parallel": "Wait", "approval": "WebHook",
            "unknown": "WebActivity"}


def _adf_ts(seconds: int) -> str:
    d, rem = divmod(seconds, 86400)
    h, rem = divmod(rem, 3600)
    m, s = divmod(rem, 60)
    return "%d.%02d:%02d:%02d" % (d, h, m, s)


def generate_adf(wf: Workflow, platform: str = "adf") -> Dict[str, dict]:
    acts = []
    for t in wf.tasks:
        deps = [{"activity": d.from_task,
                 "dependencyConditions": [
                     {"success": "Succeeded", "failure": "Failed",
                      "always": "Completed",
                      "conditional": "Succeeded",
                      "event": "Succeeded"}[d.kind]]}
                for d in wf.dependencies if d.to_task == t.key]
        atype = _ADF_OUT.get(t.type, "WebActivity")
        act: Dict[str, object] = {
            "name": t.name[:55] or t.key, "type": atype,
            "dependsOn": deps,
            "policy": {"retry": t.retry.max_attempts,
                       "retryIntervalInSeconds":
                           t.retry.interval_seconds or 30,
                       "timeout": _adf_ts(t.timeout_seconds or 7 * 86400)},
            "typeProperties": {},
        }
        tp: Dict[str, object] = act["typeProperties"]  # type: ignore
        if t.type == "sql":
            tp["scripts"] = [{"type": "Query",
                              "text": str(t.action.get("sql", "-- TODO"))}]
        elif t.type == "subworkflow":
            tp["pipeline"] = {"referenceName":
                              str(t.action.get("workflow", "TODO")),
                              "type": "PipelineReference"}
        elif t.type == "wait" or t.type in ("dummy", "parallel"):
            tp["waitTimeInSeconds"] = int(t.action.get("seconds", 1) or 1)
        elif t.type == "choice":
            tp["expression"] = {"value": t.condition or "@bool(true)",
                                "type": "Expression"}
            act["_metabridge_note"] = ("branch children must be nested "
                                       "into ifTrue/ifFalseActivities — "
                                       "see execution documentation")
        elif t.type == "loop":
            tp["items"] = {"value": str(t.loop.get("items",
                                                   "@pipeline().parameters"
                                                   ".items")),
                           "type": "Expression"}
            tp["isSequential"] = not t.loop.get("parallel", True)
        elif t.type in ("command", "email", "unknown"):
            tp["url"] = "https://TODO.invoke"
            tp["method"] = "POST"
            act["_metabridge_note"] = ("source task '%s' (%s): %s — port "
                                       "the payload to a native activity"
                                       % (t.key, t.type,
                                          json.dumps(t.action)[:150]))
        acts.append(act)
    pipeline = {"name": wf.name,
                "properties": {
                    "description": "Generated by MetaBridge AI from %s"
                                   % wf.platform,
                    "activities": acts,
                    "parameters": {v["name"]: {"type": "string",
                                               "defaultValue":
                                                   v.get("value", "")}
                                   for v in wf.variables
                                   if v.get("scope") == "parameter"},
                    "annotations": ["metabridge", wf.platform],
                }}
    out = {"%s_pipeline.json" % wf.name: pipeline}
    cron = _cron_of(wf)
    if cron:
        parts = cron.split()
        rec: Dict[str, object] = {"frequency": "Day", "interval": 1,
                                  "timeZone": "UTC"}
        if parts[1] != "*" and parts[0] != "*":
            rec["schedule"] = {"hours": [int(parts[1].split(",")[0])
                                         if parts[1].isdigit() else 0],
                               "minutes": [int(parts[0])
                                           if parts[0].isdigit() else 0]}
        trigger = {"name": "trg_%s" % wf.name,
                   "properties": {
                       "type": "ScheduleTrigger",
                       "typeProperties": {"recurrence": rec},
                       "pipelines": [{"pipelineReference": {
                           "referenceName": wf.name,
                           "type": "PipelineReference"}}],
                       "_metabridge_source_schedule": cron}}
        out["trg_%s.json" % wf.name] = trigger
    return out


# ===========================================================================
# Step Functions
# ===========================================================================

def generate_stepfunctions(wf: Workflow) -> dict:
    order = wf.execution_order()
    succ: Dict[str, List] = {}
    for d in wf.dependencies:
        succ.setdefault(d.from_task, []).append(d)
    states: Dict[str, dict] = {}
    for t in wf.tasks:
        st: Dict[str, object] = {}
        if t.type == "choice":
            choices, default = [], None
            for d in succ.get(t.key, []):
                if d.kind == "conditional" and d.condition != "default":
                    choices.append({"Variable": "$.condition",
                                    "IsPresent": True,
                                    "Next": d.to_task,
                                    "_metabridge_condition":
                                        d.condition[:200]})
                else:
                    default = d.to_task
            st = {"Type": "Choice", "Choices": choices or
                  [{"Variable": "$.ok", "BooleanEquals": True,
                    "Next": default or "Done_%s" % wf.name}]}
            if default:
                st["Default"] = default
        elif t.type == "wait":
            st = {"Type": "Wait",
                  "Seconds": int(t.action.get("seconds", 60) or 60)}
        elif t.type == "dummy":
            st = {"Type": "Pass"}
        else:
            st = {"Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke",
                  "Parameters": {"FunctionName": "TODO_%s" % t.key,
                                 "_metabridge_action": t.action}}
            if t.retry.max_attempts:
                st["Retry"] = [{"ErrorEquals": ["States.ALL"],
                                "MaxAttempts": t.retry.max_attempts,
                                "IntervalSeconds":
                                    t.retry.interval_seconds or 10,
                                "BackoffRate":
                                    t.retry.backoff_factor or 2.0}]
            if t.timeout_seconds:
                st["TimeoutSeconds"] = t.timeout_seconds
        # linear Next from success edges (first one); Catch from failure
        if t.type != "choice":
            nexts = [d for d in succ.get(t.key, []) if d.kind == "success"]
            fails = [d for d in succ.get(t.key, []) if d.kind == "failure"]
            if nexts:
                st["Next"] = nexts[0].to_task
                for extra in nexts[1:]:
                    st.setdefault("_metabridge_note", []).append(
                        "also fans out to %s — model as Parallel"
                        % extra.to_task)
            else:
                st["End"] = True
            if fails and st.get("Type") == "Task":
                st["Catch"] = [{"ErrorEquals": ["States.ALL"],
                                "Next": f.to_task} for f in fails]
        states[t.key] = st
    return {"Comment": "Generated by MetaBridge AI from %s" % wf.platform,
            "StartAt": order[0] if order else "Done",
            "States": states}


# ===========================================================================
# Control-M / AutoSys / dbt Cloud
# ===========================================================================

def generate_controlm(wf: Workflow) -> dict:
    folder: Dict[str, object] = {"Type": "Folder"}
    for t in wf.tasks:
        job: Dict[str, object] = {
            "Type": {"sql": "Job:Database:SQLScript",
                     "copy": "Job:FileTransfer",
                     "dummy": "Job:Dummy"}.get(t.type, "Job:Command")}
        cmd = str(t.action.get("command", "")
                  or t.action.get("mapping", ""))
        if job["Type"] == "Job:Command":
            job["Command"] = cmd or "echo TODO_%s" % t.key
        if t.retry.max_attempts:
            job["RerunLimit"] = {"Times": str(t.retry.max_attempts)}
        if t.resources.get("machine"):
            job["Host"] = t.resources["machine"]
        cron = _cron_of(wf)
        if cron:
            job["When"] = {"Schedule": "EVERYDAY",
                           "_metabridge_source_cron": cron}
        ins = [d for d in wf.dependencies if d.to_task == t.key]
        if ins:
            job["eventsToWaitFor"] = {
                "Type": "WaitForEvents",
                "Events": [{"Event": "%s_%s"
                            % (d.from_task, "OK" if d.kind != "failure"
                               else "FAILED")} for d in ins]}
        outs = [d for d in wf.dependencies if d.from_task == t.key]
        if outs:
            job["eventsToAdd"] = {
                "Type": "AddEvents",
                "Events": [{"Event": "%s_OK" % t.key}]}
            if any(d.kind == "failure" for d in outs):
                job["_metabridge_note"] = ("failure path: add an On/Do "
                                           "action raising %s_FAILED"
                                           % t.key)
        folder[t.key] = job
    return {wf.name: folder}


def generate_autosys(wf: Workflow) -> str:
    lines = ["/* %s — generated by MetaBridge AI from %s */"
             % (wf.name, wf.platform)]
    box = _pyid(wf.name).upper() + "_BOX"
    cron = _cron_of(wf)
    lines += ["", "insert_job: %s   job_type: b" % box]
    if cron:
        parts = cron.split()
        lines.append("date_conditions: 1")
        if parts[1].isdigit() and parts[0].isdigit():
            lines.append('start_times: "%02d:%02d"'
                         % (int(parts[1]), int(parts[0])))
        lines.append("/* source cron: %s */" % cron)
    for t in wf.tasks:
        lines += ["", "insert_job: %s   job_type: c" % _pyid(t.key).upper(),
                  "box_name: %s" % box]
        cmd = str(t.action.get("command", "")
                  or t.action.get("mapping", "")
                  or "echo TODO_%s" % t.key)
        lines.append("command: %s" % cmd[:200])
        conds = []
        for d in wf.dependencies:
            if d.to_task == t.key:
                fn = "f" if d.kind == "failure" else \
                    "d" if d.kind == "always" else "s"
                conds.append("%s(%s)" % (fn, _pyid(d.from_task).upper()))
        if conds:
            lines.append("condition: %s" % " & ".join(conds))
        if t.retry.max_attempts:
            lines.append("n_retrys: %d" % t.retry.max_attempts)
        if t.timeout_seconds:
            lines.append("term_run_time: %d"
                         % max(1, t.timeout_seconds // 60))
        if t.sla_seconds:
            lines.append("max_run_alarm: %d" % max(1, t.sla_seconds // 60))
        if t.type in ("choice", "loop", "approval", "unknown"):
            lines.append("/* MANUAL: %s task — no JIL equivalent, review */"
                         % t.type)
    return "\n".join(lines) + "\n"


def generate_dbtcloud(wf: Workflow) -> dict:
    steps = []
    for k in wf.execution_order():
        t = wf.task(k)
        if t is None:
            continue
        cmd = str(t.action.get("command", "") or t.action.get("sql", ""))
        steps.append(cmd if cmd.startswith("dbt") else
                     "# %s (%s): %s" % (t.key, t.type, cmd or "TODO"))
    job = {"name": wf.name,
           "execute_steps": steps,
           "triggers": {"schedule": bool(_cron_of(wf))},
           "settings": {"threads": 4},
           "_metabridge_note": "dbt Cloud runs steps SEQUENTIALLY — "
                               "parallel waves from the source are "
                               "serialized here."}
    cron = _cron_of(wf)
    if cron:
        job["schedule"] = {"cron": cron}
    return job


# ===========================================================================
# PowerCenter workflow XML / IDMC taskflow JSON
# ===========================================================================

def generate_powercenter_workflow(wf: Workflow) -> str:
    from xml.sax.saxutils import quoteattr
    tasks_xml, links_xml = [], []
    tasks_xml.append('    <TASK NAME="Start" TYPE="Start"/>')
    heads = {t.key for t in wf.tasks} - {d.to_task
                                         for d in wf.dependencies}
    for t in wf.tasks:
        ptype = {"mapping": "Session", "command": "Command",
                 "email": "Email", "choice": "Decision",
                 "wait": "Timer", "sensor": "Event-Wait",
                 "subworkflow": "Worklet"}.get(t.type, "Command")
        tasks_xml.append('    <TASK NAME=%s TYPE="%s"/>'
                         % (quoteattr(t.key), ptype))
    for h in sorted(heads):
        links_xml.append('    <TASKLINK FROMTASK="Start" TOTASK=%s/>'
                         % quoteattr(h))
    for d in wf.dependencies:
        cond = ' CONDITION=%s' % quoteattr(
            "$%s.Status = FAILED" % d.from_task) \
            if d.kind == "failure" else ""
        links_xml.append('    <TASKLINK FROMTASK=%s TOTASK=%s%s/>'
                         % (quoteattr(d.from_task), quoteattr(d.to_task),
                            cond))
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            "<!-- Generated by MetaBridge AI from %s — session/mapping\n"
            "     bindings must be attached in the repository -->\n"
            '<POWERMART>\n  <REPOSITORY>\n  <FOLDER NAME="MetaBridge">\n'
            '  <WORKFLOW NAME=%s ISENABLED="YES">\n%s\n%s\n'
            "  </WORKFLOW>\n  </FOLDER>\n  </REPOSITORY>\n</POWERMART>\n"
            % (wf.platform, quoteattr(wf.name),
               "\n".join(tasks_xml), "\n".join(links_xml)))


def generate_idmc_taskflow(wf: Workflow) -> dict:
    succ: Dict[str, List] = {}
    for d in wf.dependencies:
        succ.setdefault(d.from_task, []).append(d)
    steps = []
    for t in wf.tasks:
        step: Dict[str, object] = {
            "name": t.key,
            "taskType": {"mapping": "MTT", "command": "CMD",
                         "choice": "DECISION", "wait": "WAIT",
                         "email": "NOTIFICATION",
                         "parallel": "PARALLEL_PATHS",
                         "subworkflow": "SUBTASKFLOW"}.get(t.type, "CMD")}
        if t.action.get("mapping"):
            step["mappingTask"] = str(t.action["mapping"])
        if t.retry.max_attempts:
            step["maxRetries"] = t.retry.max_attempts
        nexts = [d for d in succ.get(t.key, []) if d.kind != "failure"]
        fails = [d for d in succ.get(t.key, []) if d.kind == "failure"]
        if nexts:
            step["onSuccess"] = nexts[0].to_task
            if len(nexts) > 1:
                step["_metabridge_note"] = ("fans out to %s — use "
                                            "parallel paths"
                                            % [d.to_task
                                               for d in nexts[1:]])
        if fails:
            step["onFailure"] = fails[0].to_task
        if t.type == "unknown":
            step["_metabridge_note"] = "unsupported source task — review"
        steps.append(step)
    doc = {"name": wf.name,
           "description": "Generated by MetaBridge AI from %s"
                          % wf.platform,
           "taskflow": {"steps": steps}}
    cron = _cron_of(wf)
    if cron:
        doc["schedule"] = {"cron": cron}
    return doc


# ===========================================================================
# scaffold YAML + execution documentation
# ===========================================================================

def generate_scaffold_yaml(wf: Workflow) -> str:
    import yaml
    return yaml.safe_dump({
        "workflow": wf.name,
        "source_platform": wf.platform,
        "schedule": ([s.to_dict() for s in wf.schedules] or "manual"),
        "tasks": [t.to_dict() for t in wf.tasks],
        "dependencies": [d.to_dict() for d in wf.dependencies],
        "execution_waves": wf.execution_waves(),
        "notifications": [n.to_dict() for n in wf.notifications],
    }, sort_keys=False)


def generate_execution_doc(cor: COR, intelligence: dict,
                           validation: dict) -> str:
    lines = ["# Orchestration modernization — %s" % cor.name, "",
             "Source platform: **%s** · workflows: %d · tasks: %d"
             % (cor.source_platform, len(cor.workflows),
                sum(len(w.tasks) for w in cor.workflows)), "",
             "Automation score: **%s%%** · complexity: %s (%s) · "
             "estimated effort: %sh · validation: **%s**"
             % (intelligence["automation_score"],
                intelligence["migration_complexity"],
                intelligence["complexity_level"],
                intelligence["estimated_effort_hours"],
                validation["verdict"]), ""]
    for w in cor.workflows:
        lines += ["## %s" % w.name, ""]
        if w.schedules:
            lines.append("Schedule: " + "; ".join(
                s.raw or s.cron or s.kind for s in w.schedules))
        lines += ["", "Execution order:"]
        for i, wave in enumerate(w.execution_waves()):
            lines.append("%d. %s%s" % (
                i + 1, ", ".join(wave),
                "  *(parallel)*" if len(wave) > 1 else ""))
        fails = [(d.from_task, d.to_task) for d in w.dependencies
                 if d.kind == "failure"]
        if fails:
            lines += ["", "Failure paths: " + ", ".join(
                "%s → %s" % f for f in fails)]
        lines += ["", "```mermaid", to_mermaid(w), "```", ""]
    if intelligence["manual_review_items"]:
        lines += ["## Manual review", ""]
        for m in intelligence["manual_review_items"]:
            lines.append("- **%s** %s: %s" % (m.get("workflow", ""),
                                              m.get("code", ""),
                                              m.get("message", "")))
    return "\n".join(lines) + "\n"


# ===========================================================================
# orchestrated write-out
# ===========================================================================

def generate_orchestration(cor: COR, target: str, out_dir: str) -> dict:
    """COR -> target artifacts on disk. Returns the artifact manifest."""
    from pathlib import Path
    import yaml
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: List[str] = []

    def w(name: str, content: str) -> None:
        (out / name).write_text(content)
        written.append(name)

    for wf in cor.workflows:
        if target == "airflow":
            w("dag_%s.py" % wf.name, generate_airflow(wf))
        elif target in ("adf", "fabric"):
            for fname, doc in generate_adf(wf, target).items():
                w(fname, json.dumps(doc, indent=2) + "\n")
        elif target == "stepfunctions":
            w("%s.asl.json" % wf.name,
              json.dumps(generate_stepfunctions(wf), indent=2) + "\n")
        elif target == "controlm":
            w("%s.controlm.json" % wf.name,
              json.dumps(generate_controlm(wf), indent=2) + "\n")
        elif target == "autosys":
            w("%s.jil" % wf.name, generate_autosys(wf))
        elif target == "dbtcloud":
            w("%s.dbtcloud.json" % wf.name,
              json.dumps(generate_dbtcloud(wf), indent=2) + "\n")
        elif target == "powercenter":
            w("wf_%s.xml" % wf.name, generate_powercenter_workflow(wf))
        elif target == "idmc_taskflow":
            w("%s.taskflow.json" % wf.name,
              json.dumps(generate_idmc_taskflow(wf), indent=2) + "\n")
        elif target == "scaffold":
            w("%s.pipeline.yml" % wf.name, generate_scaffold_yaml(wf))
        else:
            raise ValueError("Unknown orchestration target: %s (one of %s)"
                             % (target, ", ".join(ORCH_TARGETS)))
    return {"target": target, "files": written,
            "workflows": [wf.name for wf in cor.workflows]}
