"""Event target generators (Command 8, §5–§8) — everything FROM CER.

Broker/service targets:
    kafka / confluent    topics JSON + kafka-topics.sh + Connect configs
                         (CDC feeds re-emitted as Debezium configs) +
                         ksqlDB SQL for windowed jobs (confluent)
    pulsar               pulsar-admin script (retention, dedup, subs)
    rabbitmq             definitions.json (quorum queues, DLX, bindings,
                         permissions)
    eventhubs/servicebus ARM templates (partitions, retention, sessions
                         for FIFO, dead-lettering, maxDeliveryCount)
    kinesis              CloudFormation (shards from partitions)
    pubsub               Terraform (ordering, DLQ policy, retry)
    mqtt / iothub        topic map + IoT Hub ARM routes

Streaming engines:
    flink                Flink SQL (Kafka DDL + WATERMARK + TUMBLE/HOP/
                         SESSION windowed inserts)
    spark_streaming      PySpark Structured Streaming (withWatermark,
                         window(), checkpoints per state store)
    databricks_streaming Delta Live Tables (APPLY CHANGES INTO for CDC,
                         streaming tables for topics)
    snowflake_streaming  Snowpipe Streaming + dynamic tables SQL
    dbt_streaming        dbt models where the target supports streaming
                         materializations (limitations declared)

Semantics a target cannot express are written into the artifacts as
explicit _metabridge notes/comments (delivery downgrades, ordering,
retries) — never dropped. No pairwise converters: every generator reads
only the CER.
"""
from __future__ import annotations

import json
import re
from typing import Dict, List

from .cer import CER, Channel, StreamTransformation
from .validate import TARGET_CAPS

EVENT_TARGETS = ("kafka", "confluent", "pulsar", "rabbitmq", "eventhubs",
                 "servicebus", "kinesis", "pubsub", "mqtt", "iothub",
                 "flink", "spark_streaming", "databricks_streaming",
                 "snowflake_streaming", "dbt_streaming", "scaffold")


def _ident(s: str) -> str:
    s = re.sub(r"\W+", "_", str(s)).strip("_").lower()
    return ("t_" + s) if s and s[0].isdigit() else (s or "channel")


def _notes_for(ch: Channel, target: str) -> List[str]:
    caps = TARGET_CAPS.get(target, {})
    notes = []
    if ch.delivery == "exactly_once" and not caps.get("exactly_once"):
        notes.append("source guarantees exactly-once; %s is at-least-"
                     "once — deduplicate downstream (idempotency key)"
                     % target)
    if ch.ordering in ("fifo", "global") and not caps.get("fifo"):
        notes.append("source guarantees %s ordering — use one partition "
                     "or an ordering key on %s" % (ch.ordering, target))
    if ch.dead_letter and not caps.get("dlq_native"):
        notes.append("dead-letter route to '%s' must be implemented in "
                     "the consumer on %s" % (ch.dead_letter, target))
    return notes


# ---------------------------------------------------------------------------
# broker targets
# ---------------------------------------------------------------------------

def generate_kafka(cer: CER, flavor: str = "kafka") -> Dict[str, str]:
    topics, cmds = [], ["#!/bin/sh", "# generated by MetaBridge AI from "
                        + cer.source_platform]
    for ch in cer.channels:
        cfg: Dict[str, str] = dict(
            (k, v) for k, v in ch.properties.items() if "." in k)
        if ch.retention.time_ms:
            cfg["retention.ms"] = str(ch.retention.time_ms)
        if ch.retention.policy != "delete":
            cfg["cleanup.policy"] = ch.retention.policy
        if ch.compression:
            cfg["compression.type"] = ch.compression
        entry = {"name": ch.name, "partitions": max(1, ch.partitions),
                 "replication_factor": max(3, ch.replication)
                 if ch.replication > 1 else ch.replication,
                 "config": cfg}
        notes = _notes_for(ch, flavor)
        if ch.ordering in ("fifo", "global"):
            entry["partitions"] = 1
            notes.append("partitions forced to 1 to preserve %s "
                         "ordering" % ch.ordering)
        if notes:
            entry["_metabridge_notes"] = notes
        topics.append(entry)
        cmds.append("kafka-topics.sh --create --topic '%s' "
                    "--partitions %d --replication-factor %d %s"
                    % (ch.name, entry["partitions"],
                       entry["replication_factor"],
                       " ".join("--config %s=%s" % (k, v)
                                for k, v in cfg.items())))
    out = {"topics.json": json.dumps({"topics": topics}, indent=2) + "\n",
           "create_topics.sh": "\n".join(cmds) + "\n"}
    for cdc in cer.cdc_sources:
        cfgd = {"connector.class":
                "io.debezium.connector.%s.%sConnector" % (
                    ("postgresql", "Postgres")
                    if "postgres" in cdc.flavor else ("oracle", "Oracle")
                    if "oracle" in cdc.flavor or
                    "goldengate" in cdc.flavor else ("sqlserver",
                                                     "SqlServer")),
                "table.include.list": ",".join(cdc.tables),
                "topic.prefix": cdc.name,
                "snapshot.mode": cdc.snapshot_mode or "initial",
                "_metabridge_note": "re-platformed from %s — validate "
                "table list and credentials" % cdc.flavor}
        out["connect_%s.json" % _ident(cdc.name)] = json.dumps(
            {"name": cdc.name, "config": cfgd}, indent=2) + "\n"
    if flavor == "confluent":
        ksql = generate_ksql(cer)
        if ksql:
            out["streams.ksql"] = ksql
    return out


def generate_ksql(cer: CER) -> str:
    lines = ["-- generated by MetaBridge AI"]
    for t in cer.transformations:
        if not t.sql and not t.raw:
            continue
        if t.window is not None:
            w = t.window
            win = {"tumbling": "TUMBLING (SIZE %d SECONDS)"
                   % (w.size_ms // 1000),
                   "hopping": "HOPPING (SIZE %d SECONDS, ADVANCE BY %d "
                   "SECONDS)" % (w.size_ms // 1000,
                                 max(1, w.slide_ms // 1000)),
                   "session": "SESSION (%d SECONDS)"
                   % (max(w.gap_ms, w.size_ms) // 1000)}.get(w.kind, "")
            body = t.sql or "SELECT * FROM %s" % (t.inputs[0]
                                                  if t.inputs else "src")
            grp = (" GROUP BY " + ", ".join(t.group_by)) \
                if t.group_by and "GROUP BY" not in body.upper() else ""
            lines.append(
                "CREATE TABLE %s WITH (KAFKA_TOPIC='%s') AS\n  %s\n"
                "  WINDOW %s%s EMIT CHANGES;"
                % (_ident(t.name), t.output or t.name,
                   _strip_group(body), win, grp))
            if w.time_semantics == "event_time" and \
                    not w.watermark_delay_ms:
                lines.append("-- MANUAL: no watermark declared in the "
                             "source — late-event behaviour undefined")
        elif t.sql:
            lines.append("CREATE STREAM %s WITH (KAFKA_TOPIC='%s') AS\n"
                         "  %s EMIT CHANGES;"
                         % (_ident(t.name), t.output or t.name, t.sql))
    return "\n\n".join(lines) + "\n" if len(lines) > 1 else ""


def _strip_group(sql: str) -> str:
    return re.sub(r"\s+GROUP\s+BY\s+.+$", "", sql, flags=re.I | re.S)


def generate_rabbitmq(cer: CER) -> str:
    queues, exchanges, bindings, permissions = [], [], [], []
    for ch in cer.channels:
        args: Dict[str, object] = {}
        if ch.replication > 1:
            args["x-queue-type"] = "quorum"
        if ch.retention.time_ms:
            args["x-message-ttl"] = ch.retention.time_ms
        if ch.dead_letter:
            args["x-dead-letter-exchange"] = ch.dead_letter
        q = {"name": ch.name, "vhost": "/", "durable": True,
             "arguments": args}
        notes = _notes_for(ch, "rabbitmq")
        if ch.partitions > 1:
            notes.append("source had %d partitions — RabbitMQ queues "
                         "are single-ordered; shard across %d queues "
                         "or accept serialized consumption"
                         % (ch.partitions, ch.partitions))
        if notes:
            q["_metabridge_notes"] = notes
        queues.append(q)
    for r in cer.routing:
        if r.kind == "binding":
            bindings.append({"source": r.source, "vhost": "/",
                             "destination": r.target,
                             "destination_type": "queue",
                             "routing_key": r.condition})
        elif r.kind == "route" and r.condition.startswith("exchange:"):
            exchanges.append({"name": r.name, "vhost": "/",
                              "type": r.condition.split(":", 1)[1],
                              "durable": True})
    for s in cer.security:
        if s.kind in ("acl", "permission"):
            permissions.append({"user": s.principal, "vhost": "/",
                                "configure": "",
                                "write": s.resource or ".*",
                                "read": s.resource or ".*"})
    return json.dumps({"queues": queues, "exchanges": exchanges,
                       "bindings": bindings,
                       "permissions": permissions}, indent=2) + "\n"


def generate_pulsar(cer: CER) -> str:
    lines = ["#!/bin/sh", "# generated by MetaBridge AI",
             "pulsar-admin tenants create metabridge || true",
             "pulsar-admin namespaces create metabridge/migrated || true"]
    for ch in cer.channels:
        lines.append("pulsar-admin topics create-partitioned-topic "
                     "persistent://metabridge/migrated/%s -p %d"
                     % (_ident(ch.name), max(1, ch.partitions)))
        if ch.retention.time_ms:
            lines.append("pulsar-admin namespaces set-retention "
                         "metabridge/migrated --time %dm --size -1"
                         % (ch.retention.time_ms // 60000))
        if ch.delivery == "exactly_once":
            lines.append("pulsar-admin namespaces set-deduplication "
                         "metabridge/migrated --enable")
        for n in _notes_for(ch, "pulsar"):
            lines.append("# NOTE %s: %s" % (ch.name, n))
    for c in cer.consumers:
        for chn in c.channels:
            lines.append("# subscription: %s -> Key_Shared on %s"
                         % (c.name, chn))
    return "\n".join(lines) + "\n"


def generate_azure(cer: CER, kind: str) -> str:
    res = []
    for ch in cer.channels:
        notes = _notes_for(ch, kind)
        if kind == "eventhubs":
            res.append({
                "type": "Microsoft.EventHub/namespaces/eventhubs",
                "apiVersion": "2021-11-01",
                "name": "metabridge-ns/%s" % _ident(ch.name),
                "properties": {
                    "partitionCount": max(1, min(32, ch.partitions)),
                    "messageRetentionInDays": max(
                        1, ch.retention.time_ms // 86400000 or 1)},
                **({"_metabridge_notes": notes} if notes else {})})
        else:
            props: Dict[str, object] = {
                "maxDeliveryCount": 10, "requiresSession":
                ch.ordering in ("fifo", "global"),
                "deadLetteringOnMessageExpiration": bool(ch.dead_letter)}
            for c in cer.consumers:
                if ch.name in c.channels and c.retry.max_attempts:
                    props["maxDeliveryCount"] = c.retry.max_attempts
            res.append({
                "type": "Microsoft.ServiceBus/namespaces/queues"
                if ch.kind == "queue" else
                "Microsoft.ServiceBus/namespaces/topics",
                "apiVersion": "2021-11-01",
                "name": "metabridge-sb/%s" % _ident(ch.name),
                "properties": props,
                **({"_metabridge_notes": notes} if notes else {})})
    return json.dumps({"$schema": "https://schema.management.azure.com/"
                       "schemas/2019-04-01/deploymentTemplate.json#",
                       "contentVersion": "1.0.0.0",
                       "resources": res}, indent=2) + "\n"


def generate_kinesis(cer: CER) -> str:
    res = {}
    for ch in cer.channels:
        notes = _notes_for(ch, "kinesis")
        res["Stream" + _ident(ch.name).title().replace("_", "")] = {
            "Type": "AWS::Kinesis::Stream",
            "Properties": {"Name": _ident(ch.name),
                           "ShardCount": max(1, ch.partitions),
                           "RetentionPeriodHours": max(
                               24, ch.retention.time_ms // 3600000
                               or 24)},
            **({"Metadata": {"MetaBridgeNotes": notes}} if notes
               else {})}
    return json.dumps({"AWSTemplateFormatVersion": "2010-09-09",
                       "Resources": res}, indent=2) + "\n"


def generate_pubsub(cer: CER) -> str:
    lines = ["# generated by MetaBridge AI — terraform"]
    for ch in cer.channels:
        lines.append('resource "google_pubsub_topic" "%s" {\n'
                     '  name = "%s"\n}' % (_ident(ch.name),
                                           _ident(ch.name)))
    for c in cer.consumers:
        for chn in c.channels:
            body = ['  name  = "%s"' % _ident(c.name),
                    '  topic = google_pubsub_topic.%s.name'
                    % _ident(chn)]
            ch = cer.channel(chn)
            if ch is not None and ch.ordering in ("per_key", "fifo",
                                                  "global"):
                body.append("  enable_message_ordering = true")
            if c.retry.dead_letter:
                body.append("  dead_letter_policy {\n"
                            "    dead_letter_topic = "
                            'google_pubsub_topic.%s.id\n'
                            "    max_delivery_attempts = %d\n  }"
                            % (_ident(c.retry.dead_letter),
                               max(5, c.retry.max_attempts)))
            if c.retry.backoff_ms:
                body.append('  retry_policy {\n    minimum_backoff = '
                            '"%ds"\n  }' % max(1,
                                               c.retry.backoff_ms
                                               // 1000))
            lines.append('resource "google_pubsub_subscription" "%s" '
                         "{\n%s\n}" % (_ident(c.name), "\n".join(body)))
    return "\n\n".join(lines) + "\n"


def generate_mqtt(cer: CER, kind: str = "mqtt") -> str:
    doc: Dict[str, object] = {"generated_by": "MetaBridge AI",
                              "topics": [], "routes": []}
    for ch in cer.channels:
        doc["topics"].append({          # type: ignore[union-attr]
            "topic": ch.name,
            "qos": 2 if ch.delivery == "exactly_once" else
            1 if ch.delivery == "at_least_once" else 0})
    for r in cer.routing:
        doc["routes"].append({          # type: ignore[union-attr]
            "name": r.name, "source": r.source, "target": r.target,
            "condition": r.condition})
    for i in cer.iot_sources:
        doc.setdefault("devices", []).append(  # type: ignore[union-attr]
            {"name": i.name, "topics": i.topics, "qos": i.qos,
             "device_twin": i.device_twin})
    if kind == "iothub":
        doc["arm_routes"] = [{"name": r.name,
                              "source": "DeviceMessages",
                              "condition": r.condition or "true",
                              "endpointNames": [r.target or "events"],
                              "isEnabled": True} for r in cer.routing]
    return json.dumps(doc, indent=2) + "\n"


# ---------------------------------------------------------------------------
# streaming engines
# ---------------------------------------------------------------------------

def generate_flink(cer: CER) -> str:
    lines = ["-- Flink SQL — generated by MetaBridge AI from %s"
             % cer.source_platform]
    schema_of = {s.name: s for s in cer.schemas}
    for ch in cer.channels:
        sch = schema_of.get(ch.schema) or schema_of.get(ch.name)
        cols = ["  `%s` %s" % (f["name"],
                               {"string": "STRING", "double": "DOUBLE",
                                "long": "BIGINT", "int": "INT",
                                "boolean": "BOOLEAN"}.get(
                                    str(f.get("type", "string")).lower(),
                                    "STRING"))
                for f in (sch.fields if sch else [])] or \
            ["  `payload` STRING"]
        wm = ""
        if any(f.get("name") == "event_ts"
               for f in (sch.fields if sch else [])):
            cols.append("  `ts` AS TO_TIMESTAMP_LTZ(event_ts, 3)")
            wm = ",\n  WATERMARK FOR `ts` AS `ts` - INTERVAL '30' SECOND"
        lines.append(
            "CREATE TABLE %s (\n%s%s\n) WITH (\n"
            "  'connector' = 'kafka',\n  'topic' = '%s',\n"
            "  'properties.group.id' = 'metabridge',\n"
            "  'format' = '%s'\n);"
            % (_ident(ch.name), ",\n".join(cols), wm, ch.name,
               (sch.format if sch else "json")))
    for t in cer.transformations:
        if t.window is None or not t.inputs:
            continue
        w = t.window
        src = _ident(t.inputs[0])
        tvf = {"tumbling": "TUMBLE(TABLE %s, DESCRIPTOR(`ts`), "
               "INTERVAL '%d' SECOND)" % (src, w.size_ms // 1000),
               "hopping": "HOP(TABLE %s, DESCRIPTOR(`ts`), INTERVAL "
               "'%d' SECOND, INTERVAL '%d' SECOND)"
               % (src, max(1, w.slide_ms // 1000), w.size_ms // 1000),
               "session": "SESSION(TABLE %s, DESCRIPTOR(`ts`), "
               "INTERVAL '%d' SECOND)"
               % (src, max(w.gap_ms, w.size_ms) // 1000)}.get(w.kind)
        if not tvf:
            continue
        grp = ", ".join(["window_start", "window_end"] + t.group_by)
        aggs = ", ".join("%s" % a for a in (t.group_by or ["*"]))
        lines.append(
            "-- windowed job %s (from %s)\n"
            "INSERT INTO %s\nSELECT %s, COUNT(*) AS event_count\n"
            "FROM TABLE(%s)\nGROUP BY %s;"
            % (t.name, t.engine or cer.source_platform,
               _ident(t.output or t.name), aggs, tvf, grp))
        if not w.watermark_delay_ms and \
                w.time_semantics == "event_time":
            lines.append("-- MANUAL: source declared no watermark — "
                         "the 30s default above needs business "
                         "confirmation")
    return "\n\n".join(lines) + "\n"


def generate_spark(cer: CER, databricks: bool = False) -> str:
    lines = ['"""%s — generated by MetaBridge AI from %s."""'
             % ("Databricks streaming"
                if databricks else "Spark Structured Streaming",
                cer.source_platform),
             "from pyspark.sql import functions as F", ""]
    if databricks and cer.cdc_sources:
        lines += ["import dlt", ""]
        for cdc in cer.cdc_sources:
            for t_name in cdc.tables or [cdc.name]:
                tbl = _ident(t_name.split(".")[-1])
                lines += [
                    "@dlt.view(name='%s_changes')" % tbl,
                    "def %s_changes():" % tbl,
                    "    return (spark.readStream.format('kafka')",
                    "        .option('subscribe', '%s')"
                    % (cdc.output_channels[0] if cdc.output_channels
                       else tbl),
                    "        .load())", "",
                    "dlt.create_streaming_table('%s')" % tbl,
                    "dlt.apply_changes(target='%s', "
                    "source='%s_changes'," % (tbl, tbl),
                    "    keys=['primary_key'],  # TODO: real PK",
                    "    sequence_by='ts',",
                    "    stored_as_scd_type=1)",
                    "# CDC ordering preserved per key; snapshot mode "
                    "was '%s'" % (cdc.snapshot_mode or "unset"), ""]
    for t in cer.transformations:
        if not t.inputs:
            continue
        src = t.inputs[0]
        var = _ident(t.name)
        lines += ["%s_src = (spark.readStream.format('kafka')" % var,
                  "    .option('subscribe', '%s')" % src,
                  "    .option('startingOffsets', 'earliest')",
                  "    .load())"]
        if t.window is not None:
            w = t.window
            dur = "%d seconds" % (w.size_ms // 1000)
            wm = "%d seconds" % ((w.watermark_delay_ms or 30000) // 1000)
            win = "F.window(F.col('ts'), '%s')" % dur if \
                w.kind == "tumbling" else \
                "F.window(F.col('ts'), '%s', '%s')" % (
                    dur, "%d seconds" % (max(1, w.slide_ms // 1000))) \
                if w.kind == "hopping" else \
                "F.session_window(F.col('ts'), '%s')" % (
                    "%d seconds" % (max(w.gap_ms, w.size_ms) // 1000))
            if not w.watermark_delay_ms:
                lines.append("# MANUAL: watermark defaulted to 30s — "
                             "source declared none")
            lines += ["%s = (%s_src" % (var, var),
                      "    .withWatermark('ts', '%s')" % wm,
                      "    .groupBy(%s%s)" % (win, "".join(
                          ", F.col('%s')" % g for g in t.group_by)),
                      "    .agg(F.count('*').alias('event_count')))"]
        else:
            lines.append("%s = %s_src  # %s" % (var, var,
                                                (t.sql or t.raw)[:80]))
        ckpt = "/chk/%s" % var
        lines += ["(%s.writeStream" % var,
                  "    .option('checkpointLocation', '%s')" % ckpt,
                  "    .outputMode('update')",
                  "    .format('delta' if True else 'kafka')",
                  "    .toTable('%s'))" % _ident(t.output or t.name), ""]
    if len(lines) < 5:
        lines.append("# no streaming transformations in the import — "
                     "channels land via autoloader/connect sinks")
    return "\n".join(lines) + "\n"


def generate_snowflake_streaming(cer: CER) -> str:
    lines = ["-- Snowflake streaming — generated by MetaBridge AI"]
    for ch in cer.channels:
        tbl = _ident(ch.name)
        lines.append(
            "-- Snowpipe Streaming lands '%s' (client SDK or Kafka "
            "connector with snowflake.streaming.enable=true)\n"
            "CREATE TABLE IF NOT EXISTS raw_%s (record VARIANT, "
            "loaded_at TIMESTAMP_NTZ DEFAULT SYSDATE());"
            % (ch.name, tbl))
        if ch.is_iot:
            lines.append("ALTER TABLE raw_%s CLUSTER BY "
                         "(record:deviceId, loaded_at);  -- time-series"
                         % tbl)
    for t in cer.transformations:
        if t.window is None:
            continue
        lag = max(60, t.window.size_ms // 1000)
        lines.append(
            "CREATE OR REPLACE DYNAMIC TABLE %s\n  TARGET_LAG = '%d "
            "seconds'\n  WAREHOUSE = streaming_wh\nAS\n%s;"
            % (_ident(t.name), lag,
               t.sql or "SELECT * FROM raw_%s" % _ident(
                   t.inputs[0] if t.inputs else "events")))
        lines.append("-- window semantics (%s %dms) approximated by "
                     "TARGET_LAG — Snowflake dynamic tables are "
                     "micro-batch, not event-time windows"
                     % (t.window.kind, t.window.size_ms))
    for cdc in cer.cdc_sources:
        lines.append("-- CDC '%s': land changes via Snowpipe Streaming, "
                     "then CREATE DYNAMIC TABLE ... AS SELECT * FROM "
                     "changes QUALIFY ROW_NUMBER() OVER (PARTITION BY "
                     "primary_key ORDER BY ts DESC) = 1" % cdc.name)
    return "\n\n".join(lines) + "\n"


def generate_dbt_streaming(cer: CER) -> Dict[str, str]:
    out: Dict[str, str] = {}
    notes = ["-- dbt streaming support depends on the adapter:",
             "--   Snowflake: dynamic tables (materialized='dynamic_"
             "table'); Databricks: streaming tables/materialized views",
             "-- Row-level windows are approximated by micro-batch "
             "refresh — event-time semantics are declared, not "
             "replicated"]
    for t in cer.transformations:
        if not t.sql:
            continue
        cfg = ("{{ config(materialized='dynamic_table', "
               "target_lag='%d seconds', "
               "snowflake_warehouse='streaming_wh') }}"
               % max(60, (t.window.size_ms // 1000)
                     if t.window else 60))
        out["models/streaming/%s.sql" % _ident(t.name)] = \
            "\n".join(notes) + "\n" + cfg + "\n\n" + t.sql + "\n"
    if not out:
        out["models/streaming/README.md"] = (
            "No SQL-bearing streaming jobs in the import — broker "
            "channels are landed by ingestion tooling, not dbt.\n")
    return out


# ---------------------------------------------------------------------------
# scaffold + write-out
# ---------------------------------------------------------------------------

def generate_scaffold_yaml(cer: CER) -> str:
    import yaml
    return yaml.safe_dump(cer.to_dict(), sort_keys=False,
                          default_flow_style=False)


def generate_events(cer: CER, target: str, out_dir: str) -> dict:
    from pathlib import Path
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    files: Dict[str, str] = {}
    if target in ("kafka", "confluent"):
        files = generate_kafka(cer, target)
    elif target == "pulsar":
        files = {"create_topics.sh": generate_pulsar(cer)}
    elif target == "rabbitmq":
        files = {"definitions.json": generate_rabbitmq(cer)}
    elif target in ("eventhubs", "servicebus"):
        files = {"%s_arm.json" % target: generate_azure(cer, target)}
    elif target == "kinesis":
        files = {"kinesis_cfn.json": generate_kinesis(cer)}
    elif target == "pubsub":
        files = {"pubsub.tf": generate_pubsub(cer)}
    elif target in ("mqtt", "iothub"):
        files = {"%s_topics.json" % target: generate_mqtt(cer, target)}
    elif target == "flink":
        files = {"streaming.sql": generate_flink(cer)}
    elif target == "spark_streaming":
        files = {"streaming_job.py": generate_spark(cer)}
    elif target == "databricks_streaming":
        files = {"dlt_pipeline.py": generate_spark(cer,
                                                   databricks=True)}
    elif target == "snowflake_streaming":
        files = {"snowflake_streaming.sql":
                 generate_snowflake_streaming(cer)}
    elif target == "dbt_streaming":
        files = generate_dbt_streaming(cer)
    elif target == "scaffold":
        files = {"event_estate.yml": generate_scaffold_yaml(cer)}
    else:
        raise ValueError("Unknown event target: %s (one of %s)"
                         % (target, ", ".join(EVENT_TARGETS)))
    for name, content in files.items():
        p = out / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
    return {"target": target, "files": sorted(files)}
