"""Generate PowerCenter repository XML (POWERMART) from the IR.

Produces one folder containing source/target definitions, one mapping per IR
mapping, and a workflow whose sessions follow the pipeline DAG (serialized by
topological waves).

Port expressions arrive as canonical ANSI SQL on IR ports and are translated
to the Informatica expression language here (late binding). Anything the rule
engine cannot translate is emitted as a pass-through port, the original SQL is
preserved in the port DESCRIPTION, and a MANUAL issue is raised — optionally
routed through the LLM assist callback first.
"""
from __future__ import annotations

import datetime
import re
import xml.etree.ElementTree as ET
from typing import Callable, Dict, List, Optional
from xml.dom import minidom

from ..ir.model import (
    IssueSeverity, LoadStrategy, Mapping, Pipeline, Port, Transformation,
    TransformationType,
)
from ..sqlx.expressions import ExpressionError, sql_to_infa
from ..sqlx.type_engine import decimal_fallback

# canonical -> (PC datatype, default precision)
_PC_TYPES = {
    "string": ("string", 255),
    "integer": ("integer", 10),
    "bigint": ("bigint", 19),
    "decimal": ("decimal", 28),
    "double": ("double", 15),
    "date": ("date/time", 29),
    "timestamp": ("date/time", 29),
    "boolean": ("integer", 1),
    "binary": ("binary", 4000),
}

_PC_TX_TYPE = {
    TransformationType.SOURCE_QUALIFIER: "Source Qualifier",
    TransformationType.EXPRESSION: "Expression",
    TransformationType.FILTER: "Filter",
    TransformationType.JOINER: "Joiner",
    TransformationType.AGGREGATOR: "Aggregator",
    TransformationType.SORTER: "Sorter",
    TransformationType.UNION: "Union Transformation",
    TransformationType.LOOKUP: "Lookup Procedure",
    TransformationType.ROUTER: "Router",
    TransformationType.RANK: "Rank",
    TransformationType.SEQUENCE: "Sequence",
    TransformationType.UPDATE_STRATEGY: "Update Strategy",
}

AssistFn = Optional[Callable[[str, str], Optional[str]]]  # (sql, context) -> infa expr

# Map a canonical dialect/platform to the PowerCenter DATABASETYPE label.
# Used so generated XML reflects the ACTUAL source/target platform instead
# of a hardcoded "Oracle" on every object.
_DIALECT_TO_PC_DBTYPE = {
    "oracle": "Oracle", "snowflake": "Snowflake",
    "teradata": "Teradata", "sqlserver": "Microsoft SQL Server",
    "mssql": "Microsoft SQL Server", "synapse": "Microsoft SQL Server",
    "postgres": "ODBC", "postgresql": "ODBC", "redshift": "ODBC",
    "bigquery": "ODBC", "databricks": "ODBC", "mysql": "ODBC",
    "db2": "DB2", "netezza": "Netezza",
}


def _pc_dbtype(value: str) -> str:
    """Resolve a PowerCenter DATABASETYPE from a connector's powercenter_dbtype,
    a dialect, or a platform name. Falls back to the neutral 'ODBC' — never
    silently 'Oracle' — when the platform is unknown."""
    v = (value or "").strip()
    if not v:
        return ""
    return _DIALECT_TO_PC_DBTYPE.get(v.lower(), v)


def generate_powercenter(pipeline: Pipeline, folder_name: str = "",
                         assist: AssistFn = None) -> str:
    """Return the POWERMART XML document as a string."""
    dialect = str(pipeline.metadata.get("dialect", ""))
    meta = pipeline.metadata
    # actual source/target database types — never a blanket Oracle default.
    # Only trust an explicit connector powercenter_dbtype or the SQL dialect;
    # source_platform/target_platform can be FORMAT names (dbt/idmc) which are
    # not valid DATABASETYPE values, so they are deliberately not used here.
    src_dbtype = (_pc_dbtype(str(meta.get("source_pc_dbtype", "")))
                  or _pc_dbtype(dialect) or "ODBC")
    tgt_dbtype = (_pc_dbtype(str(meta.get("target_pc_dbtype", "")))
                  or _pc_dbtype(dialect) or src_dbtype)
    repo_dbtype = tgt_dbtype or src_dbtype or "ODBC"
    root = ET.Element("POWERMART", {
        "CREATION_DATE": datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S"),
        "REPOSITORY_VERSION": "188.97",
    })
    repo = ET.SubElement(root, "REPOSITORY", {
        "NAME": "MetaBridge AI_Repo", "VERSION": "188", "CODEPAGE": "UTF-8",
        "DATABASETYPE": repo_dbtype,
    })
    folder = ET.SubElement(repo, "FOLDER", {
        "NAME": folder_name or pipeline.name, "GROUP": "", "OWNER": "metabridge",
        "SHARED": "NOTSHARED", "DESCRIPTION": "Generated by MetaBridge AI from %s project '%s'"
        % (pipeline.source_format or "dbt", pipeline.name), "PERMISSIONS": "rwx---r--",
    })

    emitted_defs: Dict[str, bool] = {}
    for mapping in pipeline.mappings:
        _emit_source_and_target_defs(folder, mapping, pipeline, emitted_defs,
                                     src_dbtype, tgt_dbtype)
    for mapping in pipeline.mappings:
        _emit_mapping(folder, mapping, dialect, assist)
    _emit_workflow(folder, pipeline)

    _scrub_control_chars(root)
    raw = ET.tostring(root, encoding="unicode")
    pretty = minidom.parseString(raw).toprettyxml(indent="  ")
    body = "\n".join(l for l in pretty.split("\n") if l.strip() and not l.startswith("<?xml"))
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!DOCTYPE POWERMART SYSTEM "powrmart.dtd">\n' + body + "\n")


# Characters XML 1.0 cannot represent AT ALL — not even as an entity. Tab,
# newline and carriage return are legal and are left alone.
_XML_ILLEGAL = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def _scrub_control_chars(root: ET.Element) -> None:
    """Strip characters that would make the document unparseable.

    Expressions really do carry them: Oracle's INITCAP transpiles to an
    explicit delimiter set containing FORM FEED and VERTICAL TAB, and one such
    character anywhere makes the WHOLE workflow XML invalid — which used to
    take the rest of the scaffold's artifacts down with it. Replaced with a
    space rather than dropped, so a delimiter list keeps its arity.
    """
    for el in root.iter():
        for key, value in list(el.attrib.items()):
            if _XML_ILLEGAL.search(value):
                el.set(key, _XML_ILLEGAL.sub(" ", value))
        if el.text and _XML_ILLEGAL.search(el.text):
            el.text = _XML_ILLEGAL.sub(" ", el.text)


# ---------------------------------------------------------------------------
# Definitions
# ---------------------------------------------------------------------------

# PowerCenter's decimal tops out here unless the session enables high
# precision, so the shared fallback has to be clamped rather than copied.
_PC_MAX_DECIMAL = 28


def _pc_type(port: Port) -> Dict[str, str]:
    dtype, default_prec = _PC_TYPES.get(port.datatype, ("string", 255))
    prec = port.precision or default_prec
    scale = port.scale or 0
    if port.datatype == "decimal" and not port.precision:
        # An undeclared decimal is not an integer. Emitting SCALE="0" here
        # asserted it was, which contradicted the warehouse DDL for the same
        # column and would truncate every fractional value on import.
        prec, scale = decimal_fallback(_PC_MAX_DECIMAL)
    return {"DATATYPE": dtype, "PRECISION": str(prec), "SCALE": str(scale)}


def _emit_source_and_target_defs(folder: ET.Element, mapping: Mapping,
                                 pipeline: Pipeline, done: Dict[str, bool],
                                 src_dbtype: str = "ODBC",
                                 tgt_dbtype: str = "ODBC") -> None:
    for t in mapping.by_type(TransformationType.SOURCE):
        key = "SRC::" + str(t.properties.get("table", t.name))
        if key in done:
            continue
        done[key] = True
        src = ET.SubElement(folder, "SOURCE", {
            "NAME": str(t.properties.get("table", t.name)),
            "DATABASETYPE": _pc_dbtype(str(t.properties.get("database_type", "")))
            or src_dbtype,
            "DBDNAME": str(t.properties.get("database") or "SRC_DB"),
            "OWNERNAME": str(t.properties.get("schema") or ""),
            "DESCRIPTION": "", "BUSINESSNAME": "",
            "OBJECTVERSION": "1", "VERSIONNUMBER": "1",
        })
        for i, p in enumerate(t.ports, 1):
            tp = _pc_type(p)
            ET.SubElement(src, "SOURCEFIELD", {
                "NAME": p.name, "DATATYPE": tp["DATATYPE"],
                "PRECISION": tp["PRECISION"], "SCALE": tp["SCALE"],
                "FIELDNUMBER": str(i), "FIELDTYPE": "ELEMITEM",
                "KEYTYPE": "NOT A KEY", "NULLABLE": "NULL" if p.nullable else "NOTNULL",
                "LENGTH": "0", "LEVEL": "0", "OCCURS": "0", "OFFSET": "0",
                "PHYSICALLENGTH": tp["PRECISION"], "PHYSICALOFFSET": "0",
                "PICTURETEXT": "", "USAGE_FLAGS": "", "DESCRIPTION": "",
                "BUSINESSNAME": "", "FIELDPROPERTY": "0", "HIDDEN": "NO",
            })
    for t in mapping.by_type(TransformationType.TARGET):
        key = "TGT::" + str(t.properties.get("table", t.name))
        if key in done:
            continue
        done[key] = True
        tgt = ET.SubElement(folder, "TARGET", {
            "NAME": str(t.properties.get("table", t.name)),
            "DATABASETYPE": tgt_dbtype, "DESCRIPTION": "", "BUSINESSNAME": "",
            "CONSTRAINT": "", "TABLEOPTIONS": "",
            "OBJECTVERSION": "1", "VERSIONNUMBER": "1",
        })
        for p in t.ports:
            tp = _pc_type(p)
            attrs = {
                "NAME": p.name, "DATATYPE": tp["DATATYPE"],
                "PRECISION": tp["PRECISION"], "SCALE": tp["SCALE"],
                "KEYTYPE": "PRIMARY KEY" if p.name in mapping.unique_key else "NOT A KEY",
                "NULLABLE": "NULL" if p.nullable else "NOTNULL",
                "FIELDNUMBER": str(t.ports.index(p) + 1),
                "PICTURETEXT": "", "DESCRIPTION": "", "BUSINESSNAME": "",
            }
            ET.SubElement(tgt, "TARGETFIELD", attrs)


# ---------------------------------------------------------------------------
# Mapping
# ---------------------------------------------------------------------------

def _to_infa(sql_expr: str, mapping: Mapping, context: str, dialect: str,
             assist: AssistFn) -> Optional[str]:
    try:
        return sql_to_infa(sql_expr, dialect)
    except ExpressionError as e:
        if assist is not None:
            result = assist(sql_expr, context)
            if result:
                mapping.add_issue(IssueSeverity.WARNING, "LLM_CONVERTED_EXPRESSION",
                                  "Expression converted by LLM assist — verify before deploy",
                                  detail="%s  =>  %s" % (sql_expr, result))
                mapping.issues[-1].resolved_by_llm = True
                return result
        mapping.add_issue(IssueSeverity.MANUAL, "EXPRESSION_UNCONVERTED",
                          "Expression could not be converted to Informatica (%s)" % context,
                          detail="%s | %s" % (sql_expr, e),
                          suggestion="Original SQL kept in the port description; "
                                     "rebuild manually or enable --llm-assist.")
        return None


def _emit_mapping(folder: ET.Element, mapping: Mapping, dialect: str,
                  assist: AssistFn) -> None:
    mname = "m_" + mapping.name
    mp = ET.SubElement(folder, "MAPPING", {
        "NAME": mname, "DESCRIPTION": mapping.description or
        "Converted from dbt model '%s' by MetaBridge AI" % mapping.name,
        "ISVALID": "YES", "OBJECTVERSION": "1", "VERSIONNUMBER": "1",
    })

    output_tx = mapping.transformation("__OUTPUT__")
    real_txs = [t for t in mapping.transformations
                if t.name != "__OUTPUT__" and t.type not in
                (TransformationType.SOURCE, TransformationType.TARGET)]

    for t in real_txs:
        _emit_transformation(mp, t, mapping, dialect, assist)

    # INSTANCE elements
    for t in mapping.by_type(TransformationType.SOURCE):
        ET.SubElement(mp, "INSTANCE", {
            "NAME": t.name, "TRANSFORMATION_NAME": str(t.properties.get("table", t.name)),
            "TRANSFORMATION_TYPE": "Source Definition", "TYPE": "SOURCE",
            "DBDNAME": str(t.properties.get("database") or "SRC_DB"),
            "DESCRIPTION": "", "REUSABLE": "NO",
        })
    for t in real_txs:
        ET.SubElement(mp, "INSTANCE", {
            "NAME": t.name, "TRANSFORMATION_NAME": t.name,
            "TRANSFORMATION_TYPE": _PC_TX_TYPE[t.type], "TYPE": "TRANSFORMATION",
            "DESCRIPTION": "", "REUSABLE": "NO",
        })
    for t in mapping.by_type(TransformationType.TARGET):
        ET.SubElement(mp, "INSTANCE", {
            "NAME": t.name, "TRANSFORMATION_NAME": str(t.properties.get("table", t.name)),
            "TRANSFORMATION_TYPE": "Target Definition", "TYPE": "TARGET",
            "DESCRIPTION": "", "REUSABLE": "NO",
        })

    # CONNECTORs — resolve the virtual __OUTPUT__ node into direct links
    tx_by_name = {t.name: t for t in mapping.transformations}
    upstream_of_output = str(output_tx.properties.get("upstream")) if output_tx else ""

    def instance_type(name: str) -> str:
        t = tx_by_name.get(name)
        if t is None:
            return "TRANSFORMATION"
        if t.type == TransformationType.SOURCE:
            return "Source Definition"
        if t.type == TransformationType.TARGET:
            return "Target Definition"
        return _PC_TX_TYPE[t.type]

    for link in mapping.links:
        frm, to = link.from_transformation, link.to_transformation
        if to == "__OUTPUT__":
            continue
        if frm == "__OUTPUT__":
            frm = upstream_of_output
        src_t, dst_t = tx_by_name.get(frm), tx_by_name.get(to)
        if src_t is None or dst_t is None:
            continue
        src_ports = {p.name.lower() for p in src_t.ports}
        for p in dst_t.ports:
            from_field = p.name
            if p.expression and dst_t.type in (TransformationType.EXPRESSION,
                                               TransformationType.AGGREGATOR):
                continue  # computed, not connected
            if from_field.lower() not in src_ports:
                continue
            ET.SubElement(mp, "CONNECTOR", {
                "FROMFIELD": from_field, "FROMINSTANCE": frm,
                "FROMINSTANCETYPE": instance_type(frm),
                "TOFIELD": p.name, "TOINSTANCE": to,
                "TOINSTANCETYPE": instance_type(to),
            })

    for i, t in enumerate(mapping.by_type(TransformationType.TARGET), 1):
        ET.SubElement(mp, "TARGETLOADORDER", {"ORDER": str(i), "TARGETINSTANCE": t.name})

    if mapping.load_strategy == LoadStrategy.SCD2:
        mapping.add_issue(IssueSeverity.MANUAL, "SCD2_TO_POWERCENTER",
                          "SCD Type 2 requires an effective-date mapping "
                          "(lookup on current version + update strategy + "
                          "insert of new version)",
                          suggestion="Use the Slowly Changing Dimension wizard "
                                     "or the workbook skeleton; generated "
                                     "mapping loads current state only.")
    if mapping.load_strategy in (LoadStrategy.MERGE, LoadStrategy.DELETE_INSERT,
                                 LoadStrategy.SCD2):
        ET.SubElement(mp, "MAPPINGVARIABLE", {
            "NAME": "$$LAST_RUN_TS", "DATATYPE": "date/time", "PRECISION": "29",
            "SCALE": "9", "ISPARAM": "NO", "AGGFUNCTION": "MAX",
            "DEFAULTVALUE": "01/01/1970 00:00:00", "DESCRIPTION":
            "Incremental watermark maintained by MetaBridge AI conversion",
        })


def _emit_transformation(mp: ET.Element, t: Transformation, mapping: Mapping,
                         dialect: str, assist: AssistFn) -> None:
    tx = ET.SubElement(mp, "TRANSFORMATION", {
        "NAME": t.name, "TYPE": _PC_TX_TYPE[t.type], "DESCRIPTION": t.description,
        "OBJECTVERSION": "1", "REUSABLE": "NO", "VERSIONNUMBER": "1",
    })
    group_by = [str(g).lower() for g in t.properties.get("group_by", [])] \
        if t.type == TransformationType.AGGREGATOR else []

    for p in t.ports:
        tp = _pc_type(p)
        attrs = {"NAME": p.name, **tp, "PORTTYPE": "INPUT/OUTPUT",
                 "DEFAULTVALUE": "", "DESCRIPTION": "", "PICTURETEXT": ""}
        if p.expression:
            infa = _to_infa(p.expression, mapping, "%s.%s" % (t.name, p.name),
                            dialect, assist)
            attrs["PORTTYPE"] = "OUTPUT"
            attrs["EXPRESSIONTYPE"] = "GENERAL"
            if infa is not None:
                attrs["EXPRESSION"] = infa
            else:
                attrs["EXPRESSION"] = p.name  # pass-through placeholder
                attrs["DESCRIPTION"] = "REVIEW — original SQL: " + p.expression
        elif t.type in (TransformationType.EXPRESSION, TransformationType.AGGREGATOR):
            attrs["EXPRESSION"] = p.name
            attrs["EXPRESSIONTYPE"] = "GENERAL"
        if group_by:
            attrs["EXPRESSIONTYPE"] = "GROUPBY" if p.name.lower() in group_by \
                else attrs.get("EXPRESSIONTYPE", "GENERAL")
        ET.SubElement(tx, "TRANSFORMFIELD", attrs)

    _emit_table_attributes(tx, t, mapping, dialect, assist)


def _attribute_safe_sql(sql: str, dialect: str) -> str:
    """XML attribute values normalize newlines to spaces on parse, so a
    multi-line override with `--` comments would swallow everything after the
    first comment. Emit a comment-free single-line statement instead."""
    try:
        import sqlglot
        out = sqlglot.transpile(sql, read=dialect or None, pretty=False,
                                comments=False)[0]
        return " ".join(out.split())
    except Exception:  # noqa: BLE001 — fall back to a textual scrub
        import re
        no_block = re.sub(r"/\*.*?\*/", " ", sql, flags=re.DOTALL)
        lines = [re.sub(r"--.*$", "", line) for line in no_block.splitlines()]
        return " ".join(" ".join(lines).split())


def _emit_table_attributes(tx: ET.Element, t: Transformation, mapping: Mapping,
                           dialect: str, assist: AssistFn) -> None:
    def attr(name: str, value: str) -> None:
        ET.SubElement(tx, "TABLEATTRIBUTE", {"NAME": name, "VALUE": value})

    if t.type == TransformationType.SOURCE_QUALIFIER:
        override = str(t.properties.get("sql_override", "") or "")
        if override:
            attr("Sql Query", _attribute_safe_sql(override, dialect))
    elif t.type == TransformationType.FILTER:
        cond = str(t.properties.get("condition", "TRUE"))
        infa = _to_infa(cond, mapping, "%s filter condition" % t.name, dialect, assist)
        attr("Filter Condition", infa if infa is not None else "TRUE -- REVIEW: " + cond)
    elif t.type == TransformationType.JOINER:
        jt = str(t.properties.get("join_type", "INNER"))
        pc_join = {"INNER": "Normal Join", "LEFT": "Master Outer Join",
                   "RIGHT": "Detail Outer Join", "FULL": "Full Outer Join"}.get(jt, "Normal Join")
        attr("Join Type", pc_join)
        cond = str(t.properties.get("condition", ""))
        infa = _to_infa(cond, mapping, "%s join condition" % t.name, dialect, assist) if cond else ""
        attr("Join Condition", infa or cond)
    elif t.type == TransformationType.SORTER:
        keys = t.properties.get("sort_keys", []) or []
        attr("Sort Keys", ", ".join("%s %s" % (k["port"], k["order"]) for k in keys))
        if t.properties.get("distinct"):
            attr("Distinct", "YES")
    elif t.type == TransformationType.LOOKUP:
        attr("Lookup table name", str(t.properties.get("table", "")))
        attr("Lookup condition", str(t.properties.get("condition", "")))


# ---------------------------------------------------------------------------
# Workflow
# ---------------------------------------------------------------------------

def _emit_workflow(folder: ET.Element, pipeline: Pipeline) -> None:
    wf_name = "wf_" + pipeline.name
    wf = ET.SubElement(folder, "WORKFLOW", {
        "NAME": wf_name, "DESCRIPTION": "MetaBridge AI-generated orchestration "
        "(sessions serialized by dbt DAG waves)", "ISENABLED": "YES",
        "ISVALID": "YES", "REUSABLE": "NO", "SUSPEND_ON_ERROR": "NO",
        "TASKS_MUST_RUN_ON_SERVER": "NO", "VERSIONNUMBER": "1",
    })
    ET.SubElement(wf, "SCHEDULER", {
        "NAME": "Scheduler", "REUSABLE": "NO", "VERSIONNUMBER": "1",
        "DESCRIPTION": "",
    })
    start = "Start"
    ET.SubElement(wf, "TASK", {"NAME": start, "TYPE": "Start",
                               "REUSABLE": "NO", "VERSIONNUMBER": "1", "DESCRIPTION": ""})

    strategies = {m.name: m for m in pipeline.mappings}
    for m in pipeline.mappings:
        s = ET.SubElement(wf, "SESSION", {
            "NAME": "s_m_" + m.name, "MAPPINGNAME": "m_" + m.name,
            "DESCRIPTION": "", "REUSABLE": "NO", "SORTORDER": "Binary",
            "VERSIONNUMBER": "1", "ISVALID": "YES",
        })
        treat = "Insert"
        if m.load_strategy in (LoadStrategy.MERGE, LoadStrategy.SCD2):
            treat = "Update else Insert"
        elif m.load_strategy == LoadStrategy.DELETE_INSERT:
            treat = "Data driven"
        ET.SubElement(s, "ATTRIBUTE", {"NAME": "Treat source rows as", "VALUE": treat})
        if m.load_strategy == LoadStrategy.FULL:
            ET.SubElement(s, "ATTRIBUTE", {"NAME": "Truncate target table option",
                                           "VALUE": "YES"})

    prev_wave: List[str] = [start]
    for wave in pipeline.execution_order():
        for name in wave:
            if name not in strategies:
                continue
            ET.SubElement(wf, "TASKINSTANCE", {
                "NAME": "s_m_" + name, "TASKNAME": "s_m_" + name,
                "TASKTYPE": "Session", "ISENABLED": "YES", "DESCRIPTION": "",
            })
        for src in prev_wave:
            for name in wave:
                ET.SubElement(wf, "WORKFLOWLINK", {
                    "FROMTASK": src if src == start else "s_m_" + src,
                    "TOTASK": "s_m_" + name,
                    "CONDITION": "" if src == start else
                    "$s_m_%s.Status = SUCCEEDED" % src,
                })
        prev_wave = wave
