"""Union transformation handler (Phase 2, module 13).

Parses the Union's multiple INPUT groups and validates them against the
output group:

    column count            each input group must carry as many ports as
                            the output group
    datatype compatibility  per POSITION (PowerCenter matches union ports
                            positionally): identical canonical types pass;
                            numeric-family or temporal-family mixes are
                            implicit casts (warned); anything else is
                            incompatible (manual)
    port ordering           a group whose port names differ from the
                            output's at the same position still runs in
                            PowerCenter (positional), but name-based SQL
                            generation would silently swap columns — so
                            it is flagged for review

Generation contract: PowerCenter's Union is ALWAYS UNION ALL — it never
removes duplicates. UNION ALL is generated by default and a bare
(deduplicating) UNION is never emitted; if a migration genuinely needs
dedup it belongs in an explicit DISTINCT step, not the union.
"""
from __future__ import annotations

from typing import Dict, List

import xml.etree.ElementTree as ET

from ..ir.model import IssueSeverity, Mapping

_NUMERIC = {"integer", "bigint", "decimal", "double"}
_TEMPORAL = {"date", "timestamp"}


def _compatible(a: str, b: str) -> str:
    """'ok' | 'implicit' | 'incompatible' for canonical datatypes."""
    if a == b:
        return "ok"
    if a in _NUMERIC and b in _NUMERIC:
        return "implicit"
    if a in _TEMPORAL and b in _TEMPORAL:
        return "implicit"
    return "incompatible"


def enrich_union(mapping: Mapping, iname: str, props: Dict[str, object],
                 xml_t: ET.Element) -> None:
    from .powercenter_parser import _canonical

    group_names = [g.get("NAME", "") for g in xml_t.findall("GROUP")
                   if "INPUT" in (g.get("TYPE") or "").upper()]
    fields_by_group: Dict[str, List[dict]] = {g: [] for g in group_names}
    output_fields: List[dict] = []
    for f in xml_t.findall("TRANSFORMFIELD"):
        entry = {"name": f.get("NAME", ""),
                 "datatype": _canonical(f.get("DATATYPE"))}
        g = f.get("GROUP", "")
        if g in fields_by_group:
            fields_by_group[g].append(entry)
        else:
            output_fields.append(entry)

    if not group_names:
        return                      # plain union without declared groups

    for gname in group_names:
        fields = fields_by_group[gname]
        if len(fields) != len(output_fields):
            mapping.add_issue(
                IssueSeverity.MANUAL, "UNION_COLUMN_COUNT",
                "Union '%s' input group '%s' has %d port(s) but the "
                "output group has %d — the branches do not align"
                % (iname, gname, len(fields), len(output_fields)),
                suggestion="Re-export the transformation or align the "
                           "group manually before conversion.")
            continue
        for pos, (fin, fout) in enumerate(zip(fields, output_fields)):
            verdict = _compatible(fin["datatype"], fout["datatype"])
            if verdict == "implicit":
                mapping.add_issue(
                    IssueSeverity.WARNING, "UNION_TYPE_WIDENING",
                    "Union '%s' group '%s' position %d: %s (%s) unions "
                    "into %s (%s) — implicit cast"
                    % (iname, gname, pos + 1, fin["name"],
                       fin["datatype"], fout["name"], fout["datatype"]),
                    suggestion="Verify precision on the widened type.")
            elif verdict == "incompatible":
                mapping.add_issue(
                    IssueSeverity.MANUAL, "UNION_TYPE_INCOMPATIBLE",
                    "Union '%s' group '%s' position %d: %s (%s) cannot "
                    "union into %s (%s)"
                    % (iname, gname, pos + 1, fin["name"],
                       fin["datatype"], fout["name"], fout["datatype"]),
                    suggestion="Add an explicit CAST upstream of the "
                               "union branch.")
            if fin["name"].lower() != fout["name"].lower():
                mapping.add_issue(
                    IssueSeverity.WARNING, "UNION_PORT_ORDER",
                    "Union '%s' group '%s' position %d is named '%s' but "
                    "the output port is '%s' — PowerCenter matches by "
                    "POSITION; name-based SQL would swap columns"
                    % (iname, gname, pos + 1, fin["name"], fout["name"]),
                    suggestion="The generated union projects the output "
                               "column list explicitly — verify the "
                               "positional intent.")

    props["union_cir"] = {
        "operation": "UNION_ALL",       # PC Union NEVER deduplicates
        "input_groups": [{"name": g, "fields": fields_by_group[g]}
                         for g in group_names],
        "output_columns": output_fields,
    }
