-- Snowflake analytics layer — example input for:
--   metabridge convert examples/snowflake_sql -s snowflake -t dbt
CREATE TABLE RAW_EVENTS (
    EVENT_ID      NUMBER(38,0),
    USER_ID       NUMBER(38,0),
    EVENT_TYPE    VARCHAR(50),
    EVENT_TS      TIMESTAMP_NTZ,
    AMOUNT        NUMBER(18,2),
    USER_EMAIL    VARCHAR(255)
);

CREATE OR REPLACE VIEW STG_EVENTS AS
SELECT
    EVENT_ID,
    USER_ID,
    UPPER(EVENT_TYPE) AS EVENT_TYPE,
    EVENT_TS,
    CAST(AMOUNT AS DECIMAL(18,2)) AS AMOUNT,
    LOWER(USER_EMAIL) AS USER_EMAIL
FROM RAW_EVENTS
WHERE EVENT_TYPE IS NOT NULL;

CREATE TABLE DAILY_EVENT_SUMMARY AS
SELECT
    DATE_TRUNC('day', EVENT_TS) AS EVENT_DAY,
    EVENT_TYPE,
    COUNT(EVENT_ID) AS EVENT_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM STG_EVENTS
GROUP BY DATE_TRUNC('day', EVENT_TS), EVENT_TYPE;

MERGE INTO USER_ACTIVITY t
USING (
    SELECT USER_ID, MAX(EVENT_TS) AS LAST_SEEN, COUNT(EVENT_ID) AS EVENT_COUNT
    FROM STG_EVENTS
    GROUP BY USER_ID
) s
ON t.USER_ID = s.USER_ID
WHEN MATCHED THEN UPDATE SET t.LAST_SEEN = s.LAST_SEEN, t.EVENT_COUNT = s.EVENT_COUNT
WHEN NOT MATCHED THEN INSERT (USER_ID, LAST_SEEN, EVENT_COUNT)
VALUES (s.USER_ID, s.LAST_SEEN, s.EVENT_COUNT);
