"""Feasibility classification: every inventoried object, against a target.

Two sources of truth, combined:

  * **Evidence** where a definition exists — every view/materialized-view
    body is actually parsed with the source dialect and transpiled to the
    target dialect with sqlglot. A view is AUTOMATED because its SQL
    demonstrably converts, not because views are "usually fine".
  * **The matrix** for everything else — per (kind, language, target
    family): what the target equivalent is, whether the port is mechanical,
    reviewed, hand-written, or has no equivalent at all, and the effort a
    competent engineer needs.

Statuses:
    AUTOMATED      MetaBridge generates it; review is a formality
    PARTIAL        generated or directly mapped, but a human must review
    MANUAL         a known target pattern exists; a human writes it
    NO_EQUIVALENT  nothing on the target does this — declared loss/advisory

Effort figures are deterministic and explainable (hours per object by
class), the same contract as migration_intelligence — an estimate to plan
with, not a promise.
"""
from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

from ..parsers.sql_parser import SQL_DIALECT_FORMATS
from .model import ObjectInventory

# (status, target equivalent, hours, note). "*" is the fallback family.
_M: Dict[str, Dict[str, Tuple[str, str, float, str]]] = {
    "table": {
        "*": ("AUTOMATED", "landing DDL + bulk load", 0.1,
              "Generated by Pipeline Studio (ddl/ bundle)."),
    },
    "view": {   # refined per-object by transpile evidence
        "*": ("PARTIAL", "CREATE VIEW", 0.5, ""),
    },
    "materialized_view": {
        "redshift": ("PARTIAL", "materialized view", 1.0,
                     "Auto-refresh and query rewrite semantics differ."),
        "snowflake": ("PARTIAL", "materialized view", 1.0,
                      "Snowflake MVs are single-table with restrictions."),
        "bigquery": ("PARTIAL", "materialized view", 1.5,
                     "BigQuery MV restrictions (joins, non-determinism)."),
        "databricks": ("PARTIAL", "materialized view / streaming table",
                       2.0, "DLT-backed; refresh model differs."),
        "postgres": ("PARTIAL", "materialized view + scheduled REFRESH",
                     1.0, "No auto-refresh — schedule it."),
        "tsql": ("PARTIAL", "indexed view", 2.0,
                 "Indexed-view restrictions are strict."),
        "*": ("MANUAL", "summary table + scheduled rebuild", 3.0, ""),
    },
    "dynamic_table": {
        "*": ("PARTIAL", "dbt incremental model (recommended)", 1.5,
              "Or the target's materialized view where refresh semantics "
              "fit. TARGET_LAG has no direct equivalent — schedule it."),
    },
    "procedure": {   # keyed again by language below
        "*": ("PARTIAL", "stored procedure", 3.0, ""),
    },
    "function": {
        "*": ("PARTIAL", "SQL UDF", 1.0, ""),
    },
    "sequence": {
        "postgres": ("AUTOMATED", "CREATE SEQUENCE", 0.2, ""),
        "snowflake": ("AUTOMATED", "CREATE SEQUENCE", 0.2, ""),
        "tsql": ("AUTOMATED", "CREATE SEQUENCE", 0.2, ""),
        "oracle": ("AUTOMATED", "CREATE SEQUENCE", 0.2, ""),
        "redshift": ("PARTIAL", "IDENTITY column", 0.5,
                     "Gaps/concurrency semantics differ from a sequence."),
        "databricks": ("PARTIAL", "IDENTITY column", 0.5,
                       "GENERATED ALWAYS AS IDENTITY."),
        "bigquery": ("MANUAL", "GENERATE_UUID() / ROW_NUMBER pattern", 1.0,
                     "BigQuery has no sequences."),
        "*": ("MANUAL", "identity/uuid pattern", 1.0, ""),
    },
    "task": {
        "snowflake": ("AUTOMATED", "task", 0.3, ""),
        "databricks": ("PARTIAL", "Databricks Workflows job", 1.0, ""),
        "*": ("PARTIAL", "external orchestrator (Airflow/ADF/Step "
                         "Functions)", 1.0,
              "Convert with MetaBridge Orchestration modernization — the "
              "task graph maps onto COR directly."),
    },
    "stream": {
        "snowflake": ("AUTOMATED", "stream", 0.3, ""),
        "databricks": ("PARTIAL", "Delta Change Data Feed", 2.0, ""),
        "bigquery": ("PARTIAL", "change history (APPENDS TVF)", 3.0, ""),
        "tsql": ("PARTIAL", "Change Tracking / CDC", 3.0, ""),
        "redshift": ("MANUAL", "watermark/audit-column CDC or AWS DMS", 4.0,
                     "Redshift has no table-change stream."),
        "postgres": ("MANUAL", "logical decoding / trigger audit", 4.0, ""),
        "*": ("MANUAL", "CDC pattern", 4.0, ""),
    },
    "pipe": {
        "snowflake": ("AUTOMATED", "pipe (Snowpipe)", 0.3, ""),
        "redshift": ("MANUAL", "auto-copy COPY JOB or S3-event Lambda "
                     "COPY", 2.0, ""),
        "databricks": ("PARTIAL", "Auto Loader", 1.0, ""),
        "bigquery": ("PARTIAL", "Pub/Sub subscription or scheduled LOAD",
                     3.0, ""),
        "*": ("MANUAL", "event-driven load", 3.0, ""),
    },
    "stage": {
        "snowflake": ("AUTOMATED", "stage", 0.2, ""),
        "redshift": ("PARTIAL", "COPY location + IAM role", 0.5,
                     "Becomes movement settings, not an object."),
        "databricks": ("PARTIAL", "external location", 0.5, ""),
        "bigquery": ("PARTIAL", "external connection / GCS URI", 0.5, ""),
        "*": ("PARTIAL", "bulk-load location + credential", 0.5, ""),
    },
    "file_format": {
        "snowflake": ("AUTOMATED", "file format", 0.1, ""),
        "*": ("PARTIAL", "load options on COPY/LOAD", 0.2, ""),
    },
    "external_table": {
        "redshift": ("PARTIAL", "Spectrum external schema + table", 1.0,
                     ""),
        "snowflake": ("PARTIAL", "external table over a stage", 1.0, ""),
        "bigquery": ("PARTIAL", "external / BigLake table", 1.0, ""),
        "databricks": ("PARTIAL", "external table on external location",
                       0.5, ""),
        "tsql": ("PARTIAL", "PolyBase / OPENROWSET", 2.0, ""),
        "postgres": ("MANUAL", "foreign data wrapper", 2.0, ""),
        "*": ("MANUAL", "external access pattern", 2.0, ""),
    },
    "masking_policy": {
        "redshift": ("PARTIAL", "dynamic data masking policy", 1.5, ""),
        "snowflake": ("AUTOMATED", "masking policy", 0.3, ""),
        "bigquery": ("PARTIAL", "policy tags + data masking", 2.0, ""),
        "databricks": ("PARTIAL", "column mask (Unity Catalog)", 1.5, ""),
        "tsql": ("PARTIAL", "dynamic data masking", 1.5, ""),
        "postgres": ("MANUAL", "masking views / anon extension", 3.0, ""),
        "*": ("MANUAL", "masking views", 3.0, ""),
    },
    "row_access_policy": {
        "redshift": ("PARTIAL", "row-level security policy", 1.5, ""),
        "snowflake": ("AUTOMATED", "row access policy", 0.3, ""),
        "bigquery": ("PARTIAL", "row-level access policy", 1.5, ""),
        "databricks": ("PARTIAL", "row filter (Unity Catalog)", 1.5, ""),
        "tsql": ("PARTIAL", "RLS security policy", 2.0, ""),
        "postgres": ("PARTIAL", "row-level security", 1.0, ""),
        "*": ("MANUAL", "filtered views per role", 3.0, ""),
    },
    "tag": {
        "snowflake": ("AUTOMATED", "tag", 0.1, ""),
        "bigquery": ("PARTIAL", "labels / policy tags", 0.5, ""),
        "databricks": ("PARTIAL", "Unity Catalog tags", 0.3, ""),
        "*": ("MANUAL", "catalog tags (e.g. Glue) or comments", 0.5, ""),
    },
    "grant": {
        "bigquery": ("PARTIAL", "IAM bindings / dataset ACLs", 0.3,
                     "BigQuery authorization is IAM, not GRANT."),
        "*": ("AUTOMATED", "GRANT statement", 0.1,
              "Grantees (users/roles/groups) must exist on the target "
              "first — role models differ."),
    },
    "constraint": {
        # enforced targets can REJECT existing data — that demands review
        "postgres": ("PARTIAL", "enforced constraint", 0.3,
                     "Enforced on the target — validate the data first."),
        "tsql": ("PARTIAL", "enforced constraint", 0.3,
                 "Enforced on the target — validate the data first."),
        "oracle": ("PARTIAL", "enforced constraint", 0.3,
                   "Enforced on the target — validate the data first."),
        "*": ("AUTOMATED", "informational constraint", 0.1,
              "Not enforced, but the optimizer uses it for planning."),
    },
    "comment": {
        "*": ("AUTOMATED", "COMMENT ON / description", 0.05, ""),
    },
    "share": {
        "redshift": ("PARTIAL", "datashare", 2.0, ""),
        "bigquery": ("PARTIAL", "Analytics Hub listing", 2.0, ""),
        "databricks": ("PARTIAL", "Delta Sharing", 2.0, ""),
        "*": ("NO_EQUIVALENT", "", 0.0,
              "No cross-account sharing primitive on this target."),
    },
    "warehouse": {
        "*": ("NO_EQUIVALENT", "capacity sizing", 0.0,
              "Compute models differ — treat as sizing guidance, not an "
              "object to convert."),
    },
    "resource_monitor": {
        "*": ("NO_EQUIVALENT", "usage limits / budgets", 0.0,
              "Map to the target platform's cost controls manually."),
    },
}

# language overrides for code-carrying objects, keyed (kind, language)
_LANG: Dict[Tuple[str, str], Dict[str, Tuple[str, str, float, str]]] = {
    ("procedure", "sql"): {
        "redshift": ("PARTIAL", "PL/pgSQL procedure", 3.0, ""),
        "snowflake": ("PARTIAL", "SQL-scripting procedure", 3.0, ""),
        "bigquery": ("PARTIAL", "BigQuery scripting procedure", 3.0, ""),
        "postgres": ("PARTIAL", "PL/pgSQL procedure", 3.0, ""),
        "tsql": ("PARTIAL", "T-SQL procedure", 3.0, ""),
        "databricks": ("MANUAL", "notebook / DLT pipeline", 6.0,
                       "Databricks has no stored procedures — the logic "
                       "moves into a job."),
        "*": ("MANUAL", "procedural rewrite", 6.0, ""),
    },
    ("procedure", "plpgsql"): {
        "postgres": ("AUTOMATED", "PL/pgSQL procedure", 0.5, ""),
        "redshift": ("PARTIAL", "PL/pgSQL procedure", 2.0,
                     "Redshift PL/pgSQL is a subset — review built-ins."),
        "snowflake": ("PARTIAL", "SQL-scripting procedure", 3.0, ""),
        "bigquery": ("PARTIAL", "BigQuery scripting", 3.0, ""),
        "tsql": ("MANUAL", "T-SQL rewrite", 4.0, ""),
        "databricks": ("MANUAL", "notebook / job", 6.0, ""),
        "*": ("MANUAL", "procedural rewrite", 6.0, ""),
    },
    ("procedure", "javascript"): {
        "bigquery": ("MANUAL", "scripting + JS UDFs", 6.0,
                     "BigQuery JS runs in UDFs, not procedures."),
        "redshift": ("MANUAL", "Lambda UDF / Glue job", 8.0,
                     "No JavaScript runtime in Redshift."),
        "databricks": ("MANUAL", "Python/Scala notebook rewrite", 8.0, ""),
        "*": ("MANUAL", "rewrite outside the warehouse", 8.0, ""),
    },
    ("procedure", "python"): {
        "databricks": ("PARTIAL", "PySpark notebook / job", 4.0, ""),
        "snowflake": ("AUTOMATED", "Snowpark procedure", 0.5, ""),
        "redshift": ("MANUAL", "Lambda / Glue job", 8.0, ""),
        "bigquery": ("MANUAL", "remote function / Dataproc", 8.0, ""),
        "*": ("MANUAL", "external job", 8.0, ""),
    },
    ("procedure", "java"): {
        "databricks": ("PARTIAL", "JVM job", 6.0, ""),
        "*": ("MANUAL", "external JVM job", 12.0, ""),
    },
    ("procedure", "scala"): {
        "databricks": ("PARTIAL", "Scala notebook / job", 6.0, ""),
        "*": ("MANUAL", "external JVM job", 12.0, ""),
    },
    ("function", "sql"): {
        "*": ("PARTIAL", "SQL UDF", 1.0,
              "Body transpiles; verify function-name differences."),
    },
    ("function", "javascript"): {
        "bigquery": ("PARTIAL", "native JS UDF", 2.0, ""),
        "redshift": ("MANUAL", "Python UDF or Lambda UDF rewrite", 4.0, ""),
        "databricks": ("MANUAL", "Python/Scala UDF rewrite", 3.0, ""),
        "snowflake": ("AUTOMATED", "JavaScript UDF", 0.3, ""),
        "*": ("MANUAL", "UDF rewrite", 4.0, ""),
    },
    ("function", "python"): {
        "databricks": ("PARTIAL", "Python UDF", 1.0, ""),
        "redshift": ("PARTIAL", "plpythonu UDF", 2.0, ""),
        "snowflake": ("AUTOMATED", "Python UDF", 0.3, ""),
        "bigquery": ("MANUAL", "remote function", 4.0, ""),
        "*": ("MANUAL", "UDF rewrite", 4.0, ""),
    },
    ("function", "plpgsql"): {
        "postgres": ("AUTOMATED", "PL/pgSQL function", 0.3, ""),
        "redshift": ("PARTIAL", "PL/pgSQL (subset)", 1.5, ""),
        "*": ("MANUAL", "rewrite", 3.0, ""),
    },
    ("function", "plpythonu"): {
        "redshift": ("AUTOMATED", "Python UDF", 0.3, ""),
        "databricks": ("PARTIAL", "Python UDF", 1.0, ""),
        "snowflake": ("PARTIAL", "Python UDF", 1.0, ""),
        "*": ("MANUAL", "UDF rewrite", 4.0, ""),
    },
}


def _dialect_of(key: str) -> str:
    from ..connectors.base import get_registry
    spec = get_registry().get(key)
    if spec is not None and spec.dialect:
        return spec.dialect
    return SQL_DIALECT_FORMATS.get(key, "")


def _lookup(kind: str, language: str, target_family: str,
            source_key: str, target_key: str
            ) -> Tuple[str, str, float, str]:
    if source_key == target_key:
        return ("AUTOMATED", "unchanged (same platform)", 0.0, "")
    table = _LANG.get((kind, language)) or _M.get(kind) or {
        "*": ("MANUAL", "", 4.0, "Unrecognized object kind.")}
    return table.get(target_family) or table["*"]


_CREATE_VIEW_RE = re.compile(
    r"^\s*create\s+(or\s+replace\s+)?(secure\s+)?(recursive\s+)?"
    r"(materialized\s+|dynamic\s+table\b)?(view\b)?", re.I)
_IS_CREATE_RE = re.compile(r"^\s*create\b", re.I)


def transpile_view(defn: str, src_dialect: str, tgt_dialect: str,
                   qualified_name: str) -> Tuple[bool, str, str]:
    """(ok, target CREATE statement | "", reason). Evidence, not opinion:
    the body is genuinely parsed and re-rendered in the target dialect —
    and a parse that degrades to sqlglot's opaque Command node counts as
    FAILURE, because "kept the text verbatim" is not a conversion."""
    import sqlglot
    from sqlglot import exp
    text = (defn or "").strip().rstrip(";")
    if not text:
        return False, "", "definition not visible to the connected role"
    if _IS_CREATE_RE.match(text):
        body = re.sub(r"\bsecure\s+", "", text, flags=re.I)
    else:
        body = "CREATE VIEW %s AS %s" % (qualified_name, text)
    try:
        parsed = sqlglot.parse_one(body, read=src_dialect or None)
        if parsed is None or isinstance(parsed, exp.Command):
            return False, "", ("syntax the parser could not model — "
                               "convert by hand")
        # uniform, runnable output: every emitted view carries its schema,
        # whether the source stored a bare name or a qualified one
        if isinstance(parsed, exp.Create) and \
                isinstance(parsed.this, exp.Table) and \
                "." in qualified_name and not parsed.this.db:
            parsed.this.set("db", exp.to_identifier(
                qualified_name.split(".", 1)[0]))
        return True, parsed.sql(dialect=tgt_dialect or None,
                                pretty=True) + ";", ""
    except Exception as e:  # noqa: BLE001
        return False, "", str(e)[:180]


def classify_inventory(inv: ObjectInventory, source_key: str,
                       target_key: str) -> dict:
    """Every object -> a classification record; plus rollups and totals."""
    src_d = _dialect_of(source_key)
    tgt_d = _dialect_of(target_key)
    family = tgt_d or "*"
    records: List[dict] = []
    for o in inv.objects:
        status, equiv, hours, note = _lookup(o.kind, o.language, family,
                                             source_key, target_key)
        reason = note
        converted = ""
        if o.kind in ("view", "materialized_view") and \
                source_key != target_key:
            ok, sql, err = transpile_view(o.definition, src_d, tgt_d,
                                          o.qualified())
            if o.kind == "view":
                if ok:
                    status, hours = "AUTOMATED", 0.2
                    equiv = equiv or "CREATE VIEW"
                    reason = "definition transpiles cleanly to %s" % \
                        (tgt_d or target_key)
                    converted = sql
                else:
                    status, hours = "PARTIAL", 1.0
                    reason = "transpile: %s" % err
            else:                       # matrix status stands; add evidence
                if ok:
                    converted = sql
                    reason = (note + " " if note else "") + \
                        "Definition transpiles; refresh semantics need " \
                        "review."
                else:
                    reason = (note + " " if note else "") + \
                        "Transpile: %s" % err
        records.append({
            "kind": o.kind, "name": o.name, "schema": o.schema,
            "language": o.language, "status": status,
            "target_equivalent": equiv, "effort_hours": round(hours, 2),
            "reason": reason,
            **({"converted_sql": converted} if converted else {}),
        })

    by_status: Dict[str, int] = {}
    for r in records:
        by_status[r["status"]] = by_status.get(r["status"], 0) + 1
    total = len(records) or 1
    kinds: Dict[str, dict] = {}
    for r in records:
        k = kinds.setdefault(r["kind"], {
            "count": 0, "AUTOMATED": 0, "PARTIAL": 0, "MANUAL": 0,
            "NO_EQUIVALENT": 0, "effort_hours": 0.0,
            "target_equivalent": r["target_equivalent"]})
        k["count"] += 1
        k[r["status"]] += 1
        k["effort_hours"] = round(k["effort_hours"] + r["effort_hours"], 2)

    automated = by_status.get("AUTOMATED", 0)
    partial = by_status.get("PARTIAL", 0)
    return {
        "source": source_key, "target": target_key,
        "source_dialect": src_d, "target_dialect": tgt_d,
        "objects_total": len(records),
        "by_status": by_status,
        "automation_pct": round(100.0 * automated / total, 1),
        "automated_or_assisted_pct": round(
            100.0 * (automated + partial) / total, 1),
        "estimated_effort_hours": round(
            sum(r["effort_hours"] for r in records), 1),
        "kinds": {k: kinds[k] for k in sorted(kinds)},
        "records": records,
        "unreadable": inv.unreadable,
    }
