"""Object migration package: WOM + classification -> runnable target SQL.

What gets generated, and what deliberately does not:

  10_views.sql          transpiled CREATE VIEW, dependency-ordered; views
                        that failed transpile ride along as commented
                        blocks with the reason — visible, never dropped
  20_sequences.sql      sequences / identity mapping per target
  30_constraints.sql    PK/UNIQUE/FK — informational or enforced per target
  40_comments.sql       table + column comments
  50_grants.sql         translated GRANTs (grantees must exist first)
  manual_review.md      every PARTIAL/MANUAL/NO_EQUIVALENT object with its
                        preserved definition and the target pattern
  README.md             run order

Procedures, tasks, streams, pipes and policies are NOT auto-generated as
target SQL: pretending a JavaScript procedure "converted" is how migrations
fail in production. Their bodies are preserved in the manual pack with the
mapped target pattern per object.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List

from .model import DbObject, ObjectInventory

_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_$]*")


def _sql_str(v: str) -> str:
    return "'" + str(v).replace("'", "''") + "'"


def _topo_views(views: List[dict]) -> List[dict]:
    """Order views so dependencies come first. A view naming another view in
    its definition depends on it; cycles (rare, illegal anyway) fall back to
    name order at the end."""
    names = {v["name"].lower(): v for v in views}
    deps: Dict[str, set] = {}
    for v in views:
        body = (v.get("definition") or "").lower()
        toks = set(_IDENT.findall(body))
        deps[v["name"].lower()] = {
            t for t in toks if t in names and t != v["name"].lower()}
    ordered, done = [], set()
    remaining = sorted(names)
    while remaining:
        progressed = False
        for n in list(remaining):
            if deps[n] <= done:
                ordered.append(names[n])
                done.add(n)
                remaining.remove(n)
                progressed = True
        if not progressed:                      # cycle — emit rest as-is
            ordered.extend(names[n] for n in remaining)
            break
    return ordered


def _views_sql(records: List[dict], target_key: str) -> str:
    views = [r for r in records if r["kind"] == "view"]
    if not views:
        return ""
    ok = [r for r in views if r.get("converted_sql")]
    failed = [r for r in views if not r.get("converted_sql")]
    parts = ["-- Views converted to %s. Dependency-ordered: a view that"
             % target_key,
             "-- reads another view is created after it.",
             "-- Landing tables (ddl/ bundle) must exist first.", ""]
    for r in _topo_views(ok):
        parts.append("-- %s.%s" % (r["schema"], r["name"]))
        parts.append(r["converted_sql"])
        parts.append("")
    if failed:
        parts += ["-- =========================================="
                  "=================",
                  "-- NOT converted automatically — reason per view. The",
                  "-- original definitions are preserved in "
                  "manual_review.md.",
                  ""]
        for r in failed:
            # sqlglot errors embed newlines — flatten so the block stays
            # a valid SQL comment when this file runs
            reason = " ".join(str(r.get("reason", "")).split())[:200]
            parts.append("-- %s.%s: %s" % (r["schema"], r["name"], reason))
    return "\n".join(parts) + "\n"


def _sequences_sql(objs: List[DbObject], target_family: str) -> str:
    if not objs:
        return ""
    parts: List[str] = []
    for o in objs:
        start = str(o.properties.get("start", "1") or "1")
        inc = str(o.properties.get("increment", "1") or "1")
        qual = o.qualified()
        if target_family in ("postgres", "snowflake", "tsql", "oracle"):
            parts.append("CREATE SEQUENCE %s START WITH %s INCREMENT BY "
                         "%s;" % (qual, start, inc))
        elif target_family in ("redshift", "databricks"):
            parts.append("-- %s: no sequences on this target. Use an "
                         "IDENTITY column on the consuming table:" % qual)
            parts.append("--   <column> BIGINT GENERATED BY DEFAULT AS "
                         "IDENTITY (START WITH %s INCREMENT BY %s)"
                         % (start, inc))
        else:
            parts.append("-- %s: no sequences on this target — use a "
                         "GENERATE_UUID()/ROW_NUMBER pattern." % qual)
    head = ["-- Sequences. Identity semantics differ (gaps, concurrency,",
            "-- restart) — verify consumers do not assume gap-free values.",
            ""]
    return "\n".join(head + parts) + "\n"


def _constraints_sql(objs: List[DbObject], target_family: str) -> str:
    if not objs:
        return ""
    enforced = target_family in ("postgres", "tsql", "oracle")
    parts = ["-- Constraints. On %s these are %s." % (
        target_family or "the target",
        "ENFORCED — validate the data first or ADD will fail" if enforced
        else "informational: not enforced, but the optimizer uses them"),
        ""]
    for o in objs:
        p = o.properties
        table = str(p.get("table", "") or "")
        cols = [str(c) for c in (p.get("columns") or []) if c]
        ctype = str(p.get("constraint_type", "") or "").upper()
        if not table or not cols:
            parts.append("-- %s on %s: column list not readable — declare "
                         "by hand" % (ctype or "constraint",
                                      table or o.name))
            continue
        qual = "%s.%s" % (o.schema, table) if o.schema else table
        collist = ", ".join(cols)
        if ctype == "PRIMARY KEY":
            stmt = "ALTER TABLE %s ADD PRIMARY KEY (%s)" % (qual, collist)
        elif ctype == "UNIQUE":
            stmt = "ALTER TABLE %s ADD UNIQUE (%s)" % (qual, collist)
        elif ctype == "FOREIGN KEY":
            ref_t = str(p.get("ref_table", "") or "")
            ref_c = [str(c) for c in (p.get("ref_columns") or []) if c]
            if not ref_t or not ref_c:
                parts.append("-- FK %s on %s: referenced table/columns not "
                             "readable — declare by hand" % (o.name, qual))
                continue
            ref_q = "%s.%s" % (o.schema, ref_t) if o.schema else ref_t
            stmt = ("ALTER TABLE %s ADD FOREIGN KEY (%s) REFERENCES "
                    "%s (%s)" % (qual, collist, ref_q, ", ".join(ref_c)))
        else:
            continue
        if target_family == "bigquery":
            stmt += " NOT ENFORCED"
        parts.append(stmt + ";")
    return "\n".join(parts) + "\n"


def _comments_sql(objs: List[DbObject], target_family: str) -> str:
    if not objs:
        return ""
    parts = ["-- Descriptions carried from the source catalog.", ""]
    for o in objs:
        text = _sql_str(o.definition)
        on = str(o.properties.get("on", "table"))
        qual = o.qualified()
        if target_family == "bigquery":
            if on == "table":
                parts.append("ALTER TABLE %s SET OPTIONS (description = "
                             "%s);" % (qual, text))
            else:
                tbl, col = qual.rsplit(".", 1)
                parts.append("ALTER TABLE %s ALTER COLUMN %s SET OPTIONS "
                             "(description = %s);" % (tbl, col, text))
        elif target_family == "tsql":
            parts.append("-- %s %s: use sp_addextendedproperty "
                         "(MS_Description) — no COMMENT ON in T-SQL"
                         % (on, qual))
        else:
            kw = "TABLE" if on == "table" else "COLUMN"
            parts.append("COMMENT ON %s %s IS %s;" % (kw, qual, text))
    return "\n".join(parts) + "\n"


# privileges portable enough to translate 1:1 at table level
_PORTABLE_PRIVS = {"SELECT", "INSERT", "UPDATE", "DELETE", "REFERENCES",
                   "TRUNCATE", "USAGE", "ALL"}


def _grants_sql(objs: List[DbObject], target_family: str) -> str:
    if not objs:
        return ""
    if target_family == "bigquery":
        return ("-- BigQuery authorization is IAM, not GRANT. The source\n"
                "-- privileges are listed in manual_review.md — map each\n"
                "-- grantee to an IAM principal and bind dataset/table "
                "roles.\n")
    parts = ["-- Grants translated from the source catalog.",
             "-- The grantees (users/roles/groups) must exist on the "
             "target",
             "-- FIRST — role models differ between platforms, so create "
             "them",
             "-- deliberately rather than mechanically.", ""]
    seen = set()
    skipped = 0
    for o in objs:
        p = o.properties
        priv = str(p.get("privilege", "")).upper()
        grantee = str(p.get("grantee", "") or "")
        if not grantee or priv not in _PORTABLE_PRIVS:
            skipped += 1
            continue
        qual = o.qualified()
        sig = (priv, qual, grantee)
        if sig in seen:
            continue
        seen.add(sig)
        parts.append("GRANT %s ON %s TO %s;" % (priv, qual, grantee))
    if skipped:
        parts.append("-- %d grant(s) skipped (platform-specific privilege "
                     "or empty grantee) — see manual_review.md" % skipped)
    return "\n".join(parts) + "\n"


def _manual_md(records: List[dict], inv: ObjectInventory,
               target_key: str) -> str:
    by_name = {(o.kind, o.schema, o.name): o for o in inv.objects}
    manual = [r for r in records
              if r["status"] in ("PARTIAL", "MANUAL", "NO_EQUIVALENT")
              and r["kind"] not in ("table", "grant", "comment")]
    lines = ["# Manual review — %s" % target_key, "",
             "Every object below needs a decision or a human port. The "
             "original definition is preserved in full — nothing was "
             "dropped silently.", ""]
    if not manual:
        lines.append("Nothing to review — every object converted "
                     "automatically.")
        return "\n".join(lines) + "\n"
    by_kind: Dict[str, List[dict]] = {}
    for r in manual:
        by_kind.setdefault(r["kind"], []).append(r)
    for kind in sorted(by_kind):
        rows = by_kind[kind]
        lines += ["## %s (%d)" % (kind.replace("_", " "), len(rows)), ""]
        for r in rows:
            qual = "%s.%s" % (r["schema"], r["name"]) if r["schema"] \
                else r["name"]
            lines.append("### `%s`%s — **%s**" % (
                qual, " (%s)" % r["language"] if r["language"] else "",
                r["status"]))
            if r.get("target_equivalent"):
                lines.append("Target pattern: %s" % r["target_equivalent"])
            if r.get("reason"):
                lines.append("Why: %s" % r["reason"])
            lines.append("Estimated effort: %sh" % r["effort_hours"])
            o = by_name.get((r["kind"], r["schema"], r["name"]))
            if o is not None and o.definition:
                lines += ["", "```sql", o.definition.strip()[:8000], "```"]
            if o is not None and o.properties:
                keep = {k: v for k, v in o.properties.items()
                        if k not in ("columns",)}
                if keep:
                    lines.append("Properties: " + ", ".join(
                        "%s=%s" % (k, v) for k, v in keep.items()))
            lines.append("")
    return "\n".join(lines) + "\n"


def generate_object_package(inv: ObjectInventory, classification: dict,
                            target_key: str, out_dir: str) -> dict:
    """Write the package. -> manifest {files, generated, manual}."""
    from .feasibility import _dialect_of
    family = _dialect_of(target_key) or "*"
    records = classification["records"]
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    by_kind = inv.by_kind()
    files: List[str] = []

    def emit(name: str, text: str) -> None:
        if text:
            (out / name).write_text(text, encoding="utf-8")
            files.append(name)

    emit("10_views.sql", _views_sql(records, target_key))
    emit("20_sequences.sql",
         _sequences_sql(by_kind.get("sequence", []), family))
    emit("30_constraints.sql",
         _constraints_sql(by_kind.get("constraint", []), family))
    emit("40_comments.sql",
         _comments_sql(by_kind.get("comment", []), family))
    emit("50_grants.sql", _grants_sql(by_kind.get("grant", []), family))
    emit("manual_review.md", _manual_md(records, inv, target_key))

    views_ok = sum(1 for r in records
                   if r["kind"] == "view" and r.get("converted_sql"))
    views_manual = sum(1 for r in records
                       if r["kind"] == "view"
                       and not r.get("converted_sql"))
    manual_total = sum(1 for r in records
                       if r["status"] in ("PARTIAL", "MANUAL",
                                          "NO_EQUIVALENT")
                       and r["kind"] not in ("table", "grant", "comment"))
    readme = [
        "# Object migration package — %s to %s" % (inv.connector,
                                                   target_key), "",
        "Run AFTER the landing layer (Pipeline Studio's ddl/ bundle): "
        "views select from the landed tables.", "",
        "Run in file order:", "",
    ]
    for f in files:
        if f.endswith(".sql"):
            readme.append("1. `%s`" % f)
    readme += ["", "Then work through `manual_review.md` — %d object(s) "
               "need a human decision." % manual_total, "",
               "Views: %d converted automatically, %d in the manual "
               "queue." % (views_ok, views_manual)]
    (out / "README.md").write_text("\n".join(readme) + "\n",
                                   encoding="utf-8")
    files.append("README.md")
    return {"files": files, "views_converted": views_ok,
            "views_manual": views_manual, "manual_objects": manual_total}
